# Structured Data Extraction from Rectal Cancer MRI Reports

## Project Overview

This notebook tackles the problem of **automatically extracting structured clinical fields from free-text rectal cancer MRI reports**. Each report must be parsed into **54 standardised fields** covering patient demographics, tumour measurements, MRI staging, anatomical involvement, and TNM classification.

### Dataset
| Split | Reports |
|-------|---------|
| Train | 65 |
| Validation | 20 |
| Test | 40 |

### Challenge
The dataset is extremely small (65 training reports), making supervised fine-tuning data-starved. We progressively explore multiple strategies — from classical baselines to transformer fine-tuning to LLM-based extraction — measuring accuracy at each step.

### Approach Summary
1. **Baselines** — Majority-class and TF-IDF classifiers
2. **Flan-T5-Base fine-tuning** (248M parameters) with field-by-field prompting
3. **Extended training** and improved post-processing
4. **Smart per-field ensemble** — picking the best model per field
5. **Flan-T5-Large** (780M parameters) and best-of-3 ensemble
6. **Rule-based constraint layer** — domain knowledge post-corrections
7. **LLM few-shot extraction** with Gemini 2.0 Flash (retrieval-augmented)

---

## Step 1: Install Dependencies

The cell below installs pinned versions of all required libraries: `transformers` for Flan-T5, `datasets` and `accelerate` for Hugging Face compatibility, `scikit-learn` for baselines, and `sentencepiece` for T5 tokenisation.

In [2]:
!pip install -q numpy==2.0.2 pandas==2.2.2 scikit-learn==1.5.2 transformers==4.41.2 datasets==2.19.1 accelerate==0.30.1 sentencepiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 54.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 79.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.6/302.6 kB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 50.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 96.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.3.1 which is incompatibl

## Step 2: Import Libraries & Set Random Seeds

We import all necessary libraries and fix random seeds (`SEED=42`) across Python, NumPy, and PyTorch to ensure reproducible results. The code also detects whether a GPU is available and prints the device name.

In [3]:
import ast, json, math, random, re, os, copy, platform
from collections import OrderedDict
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import accuracy_score, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression, Ridge
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, get_linear_schedule_with_warmup

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device:', device)
if torch.cuda.is_available(): print('GPU:', torch.cuda.get_device_name(0))

Device: cuda
GPU: NVIDIA A100-SXM4-40GB


## Step 3: Load Data & Define the Extraction Schema

This is a critical setup cell that:

1. **Loads the train/valid/test CSV files** — each row contains a report ID, the free-text MRI report, and a nested Python dict (as a string) holding the ground-truth labels.

2. **Defines the full schema** with 54 fields organised hierarchically: patient bio (age, gender), 13 numeric MRI measurements, 5 MRI stage flags, imaging findings (T2 signal, DWI, morphology), post-treatment changes, perforation status, anatomical involvement (gender-specific and shared structures), sphincter complex fields, and TNM staging with MR TRG.

3. **Flattens the nested output dicts** into a tabular format (`train_flat`, `valid_flat`, `test_flat`) where each column is one of the 54 extraction fields. This flat representation is used by all downstream models.

4. **Categorises the 54 fields** into 41 categorical and 13 numeric fields, which require different handling during training and evaluation.

In [4]:
# Load CSVs
train_df = pd.read_csv('/content/train.csv')
valid_df = pd.read_csv('/content/valid.csv')
test_df  = pd.read_csv('/content/test.csv')
print('train:', train_df.shape, 'valid:', valid_df.shape, 'test:', test_df.shape)

# Schema constants
MISSING_MARKERS = {'Not Mentioned', 'Not Applicable', 'Not Relevant', 'Nil Significant'}

TOP_ORDER = [
    'report_type','bio','mri_numeric','mri_stage','t2_signal_intensity','dwi','morphology',
    'post_treatment_change','rectal_perforation','radial_extent','crm_or_mrf_involvement',
    'emvi','tumour_deposit','is_t4a','adjacent_structures_t4b','anal_sphincter_complex',
    't_stage','n_stage','m_stage','mr_trg'
]
BIO_ORDER = ['age','gender']
MRI_NUMERIC_ORDER = [
    'current_length_of_tumour','location_of_tumour','distance_from_anal_verge',
    'distance_from_anorectal_junction','extramural_spread_size','mr_crm_distance',
    'number_of_mesorectal_nodes','internal_iliac_nodes','size_of_obturator_nodes',
    'size_of_inguinal','size_of_external_iliac','size_of_common_iliac','size_of_para_aortic'
]
MRI_STAGE_ORDER = [
    'is_first_mri_report','is_restaging_mri_report','is_mri_report_after_neoadjuvant',
    'is_post_treatment_mri_report','is_post_operative_mri'
]
POST_TREATMENT_ORDER = [
    'is_thick_t2_hypointense_band','is_thin_t2_hypointense_band',
    'is_residual_tumor_as_first_mri','is_mucin_reaction_t2_hyper_hypo_post_treatment'
]
RECTAL_PERF_ORDER = ['obstruction','perforation']
ADJ_T4B_ORDER = {
    'male': ['prostate','seminal_vesicles'],
    'female': ['ovaries','uterus','vagina'],
    'male_and_female': ['puborectalis','levator_ani','obturator_internus','obturator_externus','piriformis'],
}
ANAL_T4B_ORDER = ['external_sphincter','inter_sphincteric_plane','ischiorectal_foss','fistula_in_ano']

NUMERIC_FIELDS = {
    'bio.age','mri_numeric.current_length_of_tumour','mri_numeric.distance_from_anal_verge',
    'mri_numeric.distance_from_anorectal_junction','mri_numeric.extramural_spread_size',
    'mri_numeric.mr_crm_distance','mri_numeric.number_of_mesorectal_nodes',
    'mri_numeric.internal_iliac_nodes','mri_numeric.size_of_obturator_nodes',
    'mri_numeric.size_of_inguinal','mri_numeric.size_of_external_iliac',
    'mri_numeric.size_of_common_iliac','mri_numeric.size_of_para_aortic',
}

# Helper functions
def normalize_common_label(s):
    s = re.sub(r'\s+', ' ', str(s).strip())
    low = s.lower()
    if low == 'not relevant': return 'Not Relevant'
    if low == 'not mentioned': return 'Not Mentioned'
    if low == 'not applicable': return 'Not Applicable'
    if low == 'nil significant': return 'Nil Significant'
    s = re.sub(r'\bMR\s*TRG\b', 'MR TRG', s, flags=re.IGNORECASE)
    return s

def canonicalize_value(v):
    if v is None: return 'Not Mentioned'
    if isinstance(v, float) and str(v) == 'nan': return 'Not Mentioned'
    if isinstance(v, (int, float)): return v
    s = normalize_common_label(v)
    s = re.sub(r'(\d)(mm|cm)\b', r'\1 \2', s, flags=re.IGNORECASE)
    s = re.sub(r'\bMM\b', 'mm', s)
    s = re.sub(r'\bCM\b', 'cm', s)
    return s

def parse_output(output_str):
    return ast.literal_eval(output_str)

def ensure_schema(d):
    d = dict(d)
    if 'mri_numeric' in d:
        mn = dict(d['mri_numeric'])
        if 'location_of_tumour' not in mn:
            mn['location_of_tumour'] = 'Not Mentioned'
        d['mri_numeric'] = mn
    return d

def ordered_schema_dict(d):
    d = ensure_schema(d)
    out = OrderedDict()
    for k in TOP_ORDER:
        v = d.get(k, None)
        if k == 'bio':
            vv = v if isinstance(v, dict) else {}
            out[k] = OrderedDict([(bk, canonicalize_value(vv.get(bk))) for bk in BIO_ORDER])
        elif k == 'mri_numeric':
            vv = v if isinstance(v, dict) else {}
            out[k] = OrderedDict([(mk, canonicalize_value(vv.get(mk))) for mk in MRI_NUMERIC_ORDER])
        elif k == 'mri_stage':
            vv = v if isinstance(v, dict) else {}
            out[k] = OrderedDict([(mk, canonicalize_value(vv.get(mk))) for mk in MRI_STAGE_ORDER])
        elif k == 'post_treatment_change':
            vv = v if isinstance(v, dict) else {}
            out[k] = OrderedDict([(mk, canonicalize_value(vv.get(mk))) for mk in POST_TREATMENT_ORDER])
        elif k == 'rectal_perforation':
            vv = v if isinstance(v, dict) else {}
            out[k] = OrderedDict([(mk, canonicalize_value(vv.get(mk))) for mk in RECTAL_PERF_ORDER])
        elif k == 'adjacent_structures_t4b':
            vv = v if isinstance(v, dict) else {}
            adj = OrderedDict()
            for group, keys in ADJ_T4B_ORDER.items():
                sub = vv.get(group, {}) if isinstance(vv.get(group), dict) else {}
                adj[group] = OrderedDict([(sk, canonicalize_value(sub.get(sk))) for sk in keys])
            out[k] = adj
        elif k == 'anal_sphincter_complex':
            vv = v if isinstance(v, dict) else {}
            t4b = vv.get('t4b', {}) if isinstance(vv.get('t4b'), dict) else {}
            asc = OrderedDict()
            asc['internal_sphincter'] = canonicalize_value(vv.get('internal_sphincter'))
            asc['t4b'] = OrderedDict([(sk, canonicalize_value(t4b.get(sk))) for sk in ANAL_T4B_ORDER])
            out[k] = asc
        else:
            out[k] = canonicalize_value(v)
    return out

def flatten_dict(d, prefix=''):
    items = {}
    for k, v in d.items():
        key = f'{prefix}.{k}' if prefix else k
        if isinstance(v, dict):
            items.update(flatten_dict(v, key))
        else:
            items[key] = v
    return items

def parse_number_mm(value):
    if value is None: return None
    if isinstance(value, (int, float)) and not pd.isna(value): return float(value)
    s = normalize_common_label(value)
    if s in MISSING_MARKERS: return None
    low = s.lower()
    if low in {'not relevant', 'not mentioned', 'not applicable', 'nil significant'}: return None
    nums = re.findall(r'\d+(?:\.\d+)?', s)
    if not nums: return None
    x = max(float(n) for n in nums)
    if 'cm' in s.lower(): x = x * 10.0
    return x

def prepare_df(df):
    rows = []
    for _, row in df.iterrows():
        y = ordered_schema_dict(parse_output(row['output']))
        flat = flatten_dict(y)
        rows.append({'id': row['id'], 'text': row['text'],
                     'target_json': json.dumps(y, ensure_ascii=False), **flat})
    return pd.DataFrame(rows)

# BUILD FLAT DATAFRAMES
train_flat = prepare_df(train_df)
valid_flat = prepare_df(valid_df)
test_flat  = prepare_df(test_df)

ALL_FIELDS = [c for c in train_flat.columns if c not in ['id', 'text', 'target_json']]
CAT_FIELDS = [c for c in ALL_FIELDS if c not in NUMERIC_FIELDS]

print(f'Total fields: {len(ALL_FIELDS)}, Categorical: {len(CAT_FIELDS)}, Numeric: {len(NUMERIC_FIELDS)}')
print(f'train_flat: {train_flat.shape}, valid_flat: {valid_flat.shape}, test_flat: {test_flat.shape}')

train: (65, 3) valid: (20, 3) test: (40, 3)
Total fields: 54, Categorical: 41, Numeric: 13
train_flat: (65, 57), valid_flat: (20, 57), test_flat: (40, 57)


## Step 4: Define Evaluation Metrics

We define a comprehensive evaluation framework used consistently throughout all experiments:

- **Leaf-average categorical accuracy** — accuracy averaged across all categorical fields (each field weighted equally regardless of sample count)
- **Macro F1** — per-field macro-averaged F1 score, important for imbalanced classes
- **Micro categorical accuracy** — overall fraction of correct predictions across all field×sample cells
- **Record-level exact match** — fraction of reports where *every single field* is correct (the strictest metric)
- **Numeric MAE / RMSE** — for measurement fields, computed only where both true and predicted values are parseable numbers

In [5]:
def canon_text_label(x):
    return str(normalize_common_label(x)).strip().lower()

def evaluate_predictions(y_true_df, y_pred_df, cat_fields, numeric_fields):
    cat_accs, cat_f1s = [], []
    total_correct, total_count = 0, 0
    for col in cat_fields:
        yt = y_true_df[col].astype(str).map(canon_text_label).tolist()
        yp = y_pred_df[col].astype(str).map(canon_text_label).tolist()
        acc = accuracy_score(yt, yp)
        cat_accs.append(acc)
        cat_f1s.append(f1_score(yt, yp, average='macro', zero_division=0))
        total_correct += sum(a == b for a, b in zip(yt, yp))
        total_count += len(yt)
    abs_err, sq_err = [], []
    for col in numeric_fields:
        yt = y_true_df[col].map(parse_number_mm).tolist()
        yp = y_pred_df[col].map(parse_number_mm).tolist()
        for a, b in zip(yt, yp):
            if a is not None and b is not None:
                abs_err.append(abs(a - b))
                sq_err.append((a - b) ** 2)
    all_cols = cat_fields + list(numeric_fields)
    true_c, pred_c = y_true_df.copy(), y_pred_df.copy()
    for col in cat_fields:
        true_c[col] = true_c[col].astype(str).map(canon_text_label)
        pred_c[col] = pred_c[col].astype(str).map(canon_text_label)
    for col in numeric_fields:
        true_c[col] = true_c[col].astype(str)
        pred_c[col] = pred_c[col].astype(str)
    em = (true_c[all_cols].values == pred_c[all_cols].values).all(axis=1).mean()
    return {
        'leaf_avg_cat_accuracy': float(np.mean(cat_accs)),
        'leaf_avg_macro_f1': float(np.mean(cat_f1s)),
        'micro_cat_accuracy': float(total_correct / max(1, total_count)),
        'record_exact_match': float(em),
        'numeric_mae_mm': float(np.mean(abs_err)) if abs_err else None,
        'numeric_rmse_mm': float(np.sqrt(np.mean(sq_err))) if sq_err else None,
    }

def print_metrics(name, m):
    print(f'\n{name}')
    for k, v in m.items():
        print(f'  {k}: {v}')

print('Evaluation helpers ready.')

Evaluation helpers ready.


## Step 5: Baseline Models — Majority Class & TF-IDF

Before training any neural models, we establish two simple baselines to contextualise performance:

### Majority Baseline
For each field, always predict the most frequent value from the training set. For numeric fields, predict the median value. This gives us the accuracy floor — any useful model must beat this.

### TF-IDF + Logistic Regression
For each categorical field, we train an independent logistic regression classifier on TF-IDF features (unigrams + bigrams, up to 40k features). For numeric fields, we use a two-stage approach: a classifier to predict presence/absence, then Ridge regression for the value. This is a strong classical baseline that captures lexical patterns.

In [6]:
# --- Majority baseline ---
majority_pred = {}
for col in CAT_FIELDS:
    majority_pred[col] = train_flat[col].mode().iloc[0]
for col in NUMERIC_FIELDS:
    vals = train_flat[col].map(parse_number_mm).dropna()
    majority_pred[col] = f'{float(vals.median()):.1f} mm' if len(vals) else 'Not Mentioned'

def make_majority_pred(df_t):
    pred = pd.DataFrame(index=df_t.index)
    for col in CAT_FIELDS: pred[col] = majority_pred[col]
    for col in NUMERIC_FIELDS: pred[col] = majority_pred[col]
    return pred

maj_vm = evaluate_predictions(valid_flat, make_majority_pred(valid_flat), CAT_FIELDS, NUMERIC_FIELDS)
maj_tm = evaluate_predictions(test_flat, make_majority_pred(test_flat), CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('Majority — VALID', maj_vm)
print_metrics('Majority — TEST', maj_tm)

# --- TF-IDF baseline ---
tfidf_vec = TfidfVectorizer(ngram_range=(1,2), max_features=40000, min_df=1, sublinear_tf=True)
X_tr = tfidf_vec.fit_transform(train_flat['text'].astype(str))
X_va = tfidf_vec.transform(valid_flat['text'].astype(str))
X_te = tfidf_vec.transform(test_flat['text'].astype(str))

tfidf_vp = pd.DataFrame(index=valid_flat.index)
tfidf_tp = pd.DataFrame(index=test_flat.index)

for col in tqdm(CAT_FIELDS, desc='TF-IDF cat'):
    ytr = train_flat[col].astype(str)
    if ytr.nunique() < 2:
        tfidf_vp[col] = [ytr.iloc[0]] * X_va.shape[0]
        tfidf_tp[col] = [ytr.iloc[0]] * X_te.shape[0]
        continue
    clf = LogisticRegression(max_iter=3000, class_weight='balanced')
    clf.fit(X_tr, ytr)
    tfidf_vp[col] = clf.predict(X_va)
    tfidf_tp[col] = clf.predict(X_te)

for col in tqdm(sorted(NUMERIC_FIELDS), desc='TF-IDF num'):
    y_num = train_flat[col].map(parse_number_mm)
    y_pres = (~y_num.isna()).astype(int)
    pc = LogisticRegression(max_iter=3000, class_weight='balanced')
    pc.fit(X_tr, y_pres)
    vp_flag = pc.predict(X_va); tp_flag = pc.predict(X_te)
    reg = Ridge(alpha=1.0)
    mask = (~y_num.isna()).values
    if mask.sum() > 0:
        reg.fit(X_tr[mask], y_num[mask].values)
        vv = reg.predict(X_va); tv = reg.predict(X_te)
    else:
        vv = np.zeros(X_va.shape[0]); tv = np.zeros(X_te.shape[0])
    tfidf_vp[col] = [f'{max(0,float(v)):.1f} mm' if p==1 else 'Not Mentioned' for p,v in zip(vp_flag,vv)]
    tfidf_tp[col] = [f'{max(0,float(v)):.1f} mm' if p==1 else 'Not Mentioned' for p,v in zip(tp_flag,tv)]

tfidf_vm = evaluate_predictions(valid_flat, tfidf_vp, CAT_FIELDS, NUMERIC_FIELDS)
tfidf_tm = evaluate_predictions(test_flat, tfidf_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('TF-IDF — VALID', tfidf_vm)
print_metrics('TF-IDF — TEST', tfidf_tm)


Majority — VALID
  leaf_avg_cat_accuracy: 0.5963414634146341
  leaf_avg_macro_f1: 0.3395199589825148
  micro_cat_accuracy: 0.5963414634146341
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Majority — TEST
  leaf_avg_cat_accuracy: 0.6359756097560976
  leaf_avg_macro_f1: 0.30659516521793745
  micro_cat_accuracy: 0.6359756097560976
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan


TF-IDF cat:   0%|          | 0/41 [00:00<?, ?it/s]

TF-IDF num:   0%|          | 0/13 [00:00<?, ?it/s]


TF-IDF — VALID
  leaf_avg_cat_accuracy: 0.7548780487804878
  leaf_avg_macro_f1: 0.5595181525982746
  micro_cat_accuracy: 0.7548780487804878
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

TF-IDF — TEST
  leaf_avg_cat_accuracy: 0.7091463414634145
  leaf_avg_macro_f1: 0.4707243586563537
  micro_cat_accuracy: 0.7091463414634146
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan


## Step 6: Prompt Engineering & Dataset Construction

This cell defines the **field-by-field prompting strategy** for Flan-T5. Instead of extracting all 54 fields at once, we create a separate prompt for each field:

```
Extract the [field description] from this rectal MRI report.
If not mentioned, answer "Not Mentioned".
If not applicable, answer "Not Applicable".
If nil significant, answer "Nil Significant".

Field: [field_name]
Report: [report text]
Answer:
```

The `FIELD_DESC` dictionary maps each of the 54 fields to a human-readable description that tells the model what to look for (e.g., `'t_stage'` → `'tumour T stage (T0, T1, T2, T3a, T3b, T3c, T3d, T4a, T4b)'`).

The `FieldByFieldDataset` class generates 54 training examples per report (one per field), yielding **3,510 training examples** from 65 reports.

In [7]:
FIELD_DESC = {
    'report_type': 'type of imaging report',
    'bio.age': 'patient age in years',
    'bio.gender': 'patient gender (Male or Female)',
    'mri_numeric.current_length_of_tumour': 'current tumour length measurement',
    'mri_numeric.location_of_tumour': 'tumour location',
    'mri_numeric.distance_from_anal_verge': 'distance from anal verge in mm',
    'mri_numeric.distance_from_anorectal_junction': 'distance from anorectal junction in mm',
    'mri_numeric.extramural_spread_size': 'extramural spread size in mm',
    'mri_numeric.mr_crm_distance': 'circumferential resection margin distance in mm',
    'mri_numeric.number_of_mesorectal_nodes': 'number or size of mesorectal nodes',
    'mri_numeric.internal_iliac_nodes': 'internal iliac lymph node size',
    'mri_numeric.size_of_obturator_nodes': 'obturator lymph node size',
    'mri_numeric.size_of_inguinal': 'inguinal lymph node size',
    'mri_numeric.size_of_external_iliac': 'external iliac lymph node size',
    'mri_numeric.size_of_common_iliac': 'common iliac lymph node size',
    'mri_numeric.size_of_para_aortic': 'para-aortic lymph node size',
    'mri_stage.is_first_mri_report': 'whether this is the first MRI report (Yes/No)',
    'mri_stage.is_restaging_mri_report': 'whether this is a restaging MRI (Yes/No)',
    'mri_stage.is_mri_report_after_neoadjuvant': 'whether MRI is after neoadjuvant therapy (Yes/No)',
    'mri_stage.is_post_treatment_mri_report': 'whether this is a post-treatment MRI (Yes/No)',
    'mri_stage.is_post_operative_mri': 'whether this is a post-operative MRI (Yes/No)',
    't2_signal_intensity': 'T2 signal intensity finding',
    'dwi': 'diffusion-weighted imaging finding',
    'morphology': 'tumour morphology',
    'post_treatment_change.is_thick_t2_hypointense_band': 'thick T2 hypointense band (Yes/No)',
    'post_treatment_change.is_thin_t2_hypointense_band': 'thin T2 hypointense band (Yes/No)',
    'post_treatment_change.is_residual_tumor_as_first_mri': 'residual tumour as in first MRI (Yes/No)',
    'post_treatment_change.is_mucin_reaction_t2_hyper_hypo_post_treatment': 'mucin reaction T2 signal post treatment',
    'rectal_perforation.obstruction': 'rectal obstruction (Yes/No)',
    'rectal_perforation.perforation': 'rectal perforation (Yes/No)',
    'radial_extent': 'radial extent of tumour',
    'crm_or_mrf_involvement': 'CRM or mesorectal fascia involvement (Yes/No)',
    'emvi': 'extramural vascular invasion (Yes/No)',
    'tumour_deposit': 'tumour deposit (Yes/No)',
    'is_t4a': 'T4a peritoneal involvement (Yes/No)',
    'adjacent_structures_t4b.male.prostate': 'prostate involvement (Yes/No/Not Applicable)',
    'adjacent_structures_t4b.male.seminal_vesicles': 'seminal vesicles involvement (Yes/No/Not Applicable)',
    'adjacent_structures_t4b.female.ovaries': 'ovaries involvement (Yes/No/Not Applicable)',
    'adjacent_structures_t4b.female.uterus': 'uterus involvement (Yes/No/Not Applicable)',
    'adjacent_structures_t4b.female.vagina': 'vagina involvement (Yes/No/Not Applicable)',
    'adjacent_structures_t4b.male_and_female.puborectalis': 'puborectalis involvement (Yes/No)',
    'adjacent_structures_t4b.male_and_female.levator_ani': 'levator ani involvement (Yes/No)',
    'adjacent_structures_t4b.male_and_female.obturator_internus': 'obturator internus involvement (Yes/No)',
    'adjacent_structures_t4b.male_and_female.obturator_externus': 'obturator externus involvement (Yes/No)',
    'adjacent_structures_t4b.male_and_female.piriformis': 'piriformis involvement (Yes/No)',
    'anal_sphincter_complex.internal_sphincter': 'internal sphincter involvement (Yes/No)',
    'anal_sphincter_complex.t4b.external_sphincter': 'external sphincter involvement (Yes/No)',
    'anal_sphincter_complex.t4b.inter_sphincteric_plane': 'inter-sphincteric plane involvement (Yes/No)',
    'anal_sphincter_complex.t4b.ischiorectal_foss': 'ischiorectal fossa involvement (Yes/No)',
    'anal_sphincter_complex.t4b.fistula_in_ano': 'fistula in ano (Yes/No)',
    't_stage': 'tumour T stage (T0, T1, T2, T3a, T3b, T3c, T3d, T4a, T4b)',
    'n_stage': 'lymph node N stage (N0, N1, N2)',
    'm_stage': 'metastasis M stage (M0, M1)',
    'mr_trg': 'MR tumour regression grade (MR TRG 1 through MR TRG 5)',
}

def make_field_prompt(report_text, field_name):
    desc = FIELD_DESC.get(field_name, field_name.replace('.', ' ').replace('_', ' '))
    return (
        f'Extract the {desc} from this rectal MRI report. '
        f'If not mentioned, answer "Not Mentioned". '
        f'If not applicable, answer "Not Applicable". '
        f'If nil significant, answer "Nil Significant".\n\n'
        f'Field: {field_name}\n\n'
        f'Report: {report_text}\n\n'
        f'Answer:'
    )

class FieldByFieldDataset(Dataset):
    def __init__(self, df_flat, fields, tokenizer, max_input_len=512, max_target_len=48):
        self.items = []
        self.tokenizer = tokenizer
        self.max_input_len = max_input_len
        self.max_target_len = max_target_len
        for _, row in df_flat.iterrows():
            text = str(row['text'])
            for field in fields:
                prompt = make_field_prompt(text, field)
                target = str(row[field])
                self.items.append((prompt, target))

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        prompt, target = self.items[idx]
        enc = self.tokenizer(prompt, max_length=self.max_input_len, truncation=True,
                             padding='max_length', return_tensors='pt')
        tgt = self.tokenizer(text_target=target, max_length=self.max_target_len,
                             truncation=True, padding='max_length', return_tensors='pt')
        labels = tgt['input_ids'].squeeze(0)
        labels[labels == self.tokenizer.pad_token_id] = -100
        return {
            'input_ids': enc['input_ids'].squeeze(0),
            'attention_mask': enc['attention_mask'].squeeze(0),
            'labels': labels,
        }

print('Prompt builder and Dataset class ready.')
print(f'Sample prompt (first 200 chars):\n{make_field_prompt("..sample report..", "t_stage")[:200]}')

Prompt builder and Dataset class ready.
Sample prompt (first 200 chars):
Extract the tumour T stage (T0, T1, T2, T3a, T3b, T3c, T3d, T4a, T4b) from this rectal MRI report. If not mentioned, answer "Not Mentioned". If not applicable, answer "Not Applicable". If nil signific


## Step 7: Fine-Tune Flan-T5-Base (248M Parameters) — Initial Training

We fine-tune `google/flan-t5-base` (248M parameters) for 6 epochs as an initial run. Key hyperparameters:

| Parameter | Value | Rationale |
|-----------|-------|-----------|
| Max input length | 512 tokens | Covers most reports |
| Max target length | 48 tokens | Sufficient for all field values |
| Batch size | 8 | Fits in GPU memory |
| Learning rate | 5e-5 | Standard for T5 fine-tuning |
| Gradient accumulation | 2 steps | Effective batch size = 16 |
| Warmup | 6% of steps | Prevents early instability |

A **layer-wise learning rate decay** (`decay=0.85`) is applied so that lower (more general) layers learn more slowly than upper (task-specific) layers. Early stopping with patience=3 prevents overfitting on our tiny dataset.

> **Observation:** The validation loss dropped steeply from 5.01 to 1.43 over 6 epochs with no sign of plateau, indicating the model was severely undertrained at this point.

In [8]:
# === CONFIG ===
MODEL_NAME = 'google/flan-t5-base'  # Use 'google/flan-t5-small' if OOM
MAX_INPUT_LEN  = 512
MAX_TARGET_LEN = 48
BATCH_SIZE     = 8
EPOCHS         = 6
LR             = 5e-5
ACCUM_STEPS    = 2
WARMUP_FRAC    = 0.06

# Load model
print(f'Loading {MODEL_NAME}...')
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(device)
print(f'Params: {sum(p.numel() for p in model.parameters()):,}')

# Build datasets
print('Building datasets...')
train_ds = FieldByFieldDataset(train_flat, ALL_FIELDS, tokenizer, MAX_INPUT_LEN, MAX_TARGET_LEN)
valid_ds = FieldByFieldDataset(valid_flat, ALL_FIELDS, tokenizer, MAX_INPUT_LEN, MAX_TARGET_LEN)
print(f'Train: {len(train_ds)} examples ({len(train_flat)} reports x {len(ALL_FIELDS)} fields)')
print(f'Valid: {len(valid_ds)} examples')

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
valid_loader = DataLoader(valid_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

# Layerwise LR decay optimizer
def get_optimizer(mdl, base_lr, decay=0.85, wd=0.01):
    no_dec = {'bias', 'LayerNorm.weight', 'layer_norm.weight'}
    groups = []
    enc_b = mdl.encoder.block; dec_b = mdl.decoder.block
    ne, nd = len(enc_b), len(dec_b)
    # Embeddings
    groups.append({'params': list(mdl.shared.parameters()), 'lr': base_lr*(decay**(ne+2)), 'weight_decay': wd})
    # Encoder
    for i, blk in enumerate(enc_b):
        lr_i = base_lr * (decay ** (ne - i))
        for n, p in blk.named_parameters():
            if not p.requires_grad: continue
            groups.append({'params': [p], 'lr': lr_i,
                          'weight_decay': 0.0 if any(nd_ in n for nd_ in no_dec) else wd})
    # Decoder
    for i, blk in enumerate(dec_b):
        lr_i = base_lr * (decay ** max(0, nd - i - 2))
        for n, p in blk.named_parameters():
            if not p.requires_grad: continue
            groups.append({'params': [p], 'lr': lr_i,
                          'weight_decay': 0.0 if any(nd_ in n for nd_ in no_dec) else wd})
    # LM head
    groups.append({'params': list(mdl.lm_head.parameters()), 'lr': base_lr*1.5, 'weight_decay': wd})
    # Final norms
    for mod in [mdl.encoder.final_layer_norm, mdl.decoder.final_layer_norm]:
        groups.append({'params': list(mod.parameters()), 'lr': base_lr, 'weight_decay': 0.0})
    return torch.optim.AdamW(groups, lr=base_lr)

optimizer = get_optimizer(model, LR)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(optimizer, int(WARMUP_FRAC * total_steps), total_steps)

# Training loop
best_val_loss = float('inf')
best_state = None
patience_ctr = 0
history = []

print(f'\nTraining: {total_steps} steps, {EPOCHS} epochs\n')

for epoch in range(1, EPOCHS + 1):
    model.train()
    total_loss = 0
    optimizer.zero_grad()
    pbar = tqdm(train_loader, desc=f'Epoch {epoch}/{EPOCHS}')
    for step, batch in enumerate(pbar):
        batch = {k: v.to(device) for k, v in batch.items()}
        out = model(**batch)
        loss = out.loss / ACCUM_STEPS
        loss.backward()
        if (step + 1) % ACCUM_STEPS == 0 or (step + 1) == len(train_loader):
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step(); scheduler.step(); optimizer.zero_grad()
        total_loss += out.loss.item()
        pbar.set_postfix(loss=f'{out.loss.item():.4f}')
    avg_train = total_loss / len(train_loader)

    model.eval()
    val_loss = 0
    with torch.no_grad():
        for batch in valid_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            val_loss += model(**batch).loss.item()
    avg_val = val_loss / len(valid_loader)
    history.append({'epoch': epoch, 'train_loss': avg_train, 'val_loss': avg_val})
    print(f'Epoch {epoch} | Train: {avg_train:.4f} | Val: {avg_val:.4f}')

    if avg_val < best_val_loss:
        best_val_loss = avg_val
        best_state = copy.deepcopy(model.state_dict())
        patience_ctr = 0
        torch.save(best_state, '/content/best_flan_t5.pt')
        print('  -> Saved best')
    else:
        patience_ctr += 1
        print(f'  -> No improvement ({patience_ctr}/3)')
        if patience_ctr >= 3:
            print('Early stopping.'); break

model.load_state_dict(best_state)
print('\nBest model loaded.')
pd.DataFrame(history)

Loading google/flan-t5-base...


Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning


Params: 247,577,856
Building datasets...
Train: 3510 examples (65 reports x 54 fields)
Valid: 1080 examples

Training: 2634 steps, 6 epochs



Epoch 1/6:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 1 | Train: 7.9185 | Val: 5.0128
  -> Saved best


Epoch 2/6:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 2 | Train: 4.9297 | Val: 3.3926
  -> Saved best


Epoch 3/6:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 3 | Train: 3.6470 | Val: 2.5489
  -> Saved best


Epoch 4/6:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 4 | Train: 2.8599 | Val: 2.0294
  -> Saved best


Epoch 5/6:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 5 | Train: 2.3282 | Val: 1.6757
  -> Saved best


Epoch 6/6:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 6 | Train: 1.9725 | Val: 1.4336
  -> Saved best

Best model loaded.


,epoch,train_loss,val_loss
0,1,7.918474,5.012761
1,2,4.929698,3.392591
2,3,3.646989,2.548921
3,4,2.859876,2.029419
4,5,2.328229,1.675726
5,6,1.972488,1.433626


## Step 8: Run Inference on Validation & Test Sets

Using the trained Flan-T5-Base model, we generate predictions for all 54 fields on both the validation (20 reports) and test (40 reports) sets. For each report, the model is queried 54 times — once per field — with beam search (`num_beams=3`) for higher-quality outputs. Predictions are batched (16 prompts per batch) for efficiency.

In [9]:
def predict_all_fields(mdl, tok, texts, fields, batch_size=16, max_input=512, max_gen=48):
    mdl.eval()
    all_results = []
    for text in tqdm(texts, desc='Predicting'):
        row = {}
        prompts = [make_field_prompt(text, f) for f in fields]
        for i in range(0, len(prompts), batch_size):
            bp = prompts[i:i+batch_size]
            bf = fields[i:i+batch_size]
            enc = tok(bp, max_length=max_input, truncation=True, padding=True,
                     return_tensors='pt').to(mdl.device)
            with torch.no_grad():
                gen = mdl.generate(**enc, max_new_tokens=max_gen, num_beams=3, early_stopping=True)
            decoded = tok.batch_decode(gen, skip_special_tokens=True)
            for field, pred in zip(bf, decoded):
                row[field] = pred.strip()
        all_results.append(row)
    return pd.DataFrame(all_results)

print('Predicting validation set...')
flan_vp_raw = predict_all_fields(model, tokenizer, valid_flat['text'].astype(str).tolist(), ALL_FIELDS)

print('Predicting test set...')
flan_tp_raw = predict_all_fields(model, tokenizer, test_flat['text'].astype(str).tolist(), ALL_FIELDS)

print('Done. Shapes:', flan_vp_raw.shape, flan_tp_raw.shape)

Predicting validation set...


Predicting:   0%|          | 0/20 [00:00<?, ?it/s]

Predicting test set...


Predicting:   0%|          | 0/40 [00:00<?, ?it/s]

Done. Shapes: (20, 54) (40, 54)


## Step 9: Post-Processing, Normalisation & Initial Ensemble

### Post-Processing
Raw model outputs need normalisation because T5 may generate slight variants (e.g., `"not mentioned"` vs `"Not Mentioned"`, or `"nil"` instead of `"Nil Significant"`). The `normalize_prediction` function:
- Maps common aliases and abbreviations to canonical forms
- Matches predictions against known values from the training set (exact + substring matching)
- For numeric fields, extracts numbers and formats them as `"X mm"`
- Falls back to token-overlap matching for ambiguous predictions

### Initial TF-IDF Ensemble
For "rare" fields — where >90% of training values are missing markers — the neural model struggles with limited positive examples. We substitute TF-IDF classifier predictions for these fields, creating a simple two-model ensemble.

In [10]:
# --- Post-processing ---
def normalize_prediction(pred_str, field, tf):
    pred = str(pred_str).strip()
    pl = pred.lower()
    mm = {
        'not mentioned':'Not Mentioned', 'not applicable':'Not Applicable',
        'not relevant':'Not Relevant', 'nil significant':'Nil Significant',
        'nil':'Nil Significant', 'none':'Not Mentioned', 'n/a':'Not Applicable',
        'na':'Not Applicable', 'unknown':'Not Mentioned', 'no':'No', 'yes':'Yes',
        'male':'Male', 'female':'Female',
    }
    if pl in mm: return mm[pl]
    known = {v.strip().lower(): v for v in tf[field].astype(str).unique()}
    if pl in known: return known[pl]
    for kl, kv in known.items():
        if len(kl) > 2 and (kl in pl or pl in kl): return kv
    if field in NUMERIC_FIELDS:
        nums = re.findall(r'\d+(?:\.\d+)?', pred)
        if nums:
            val = max(float(n) for n in nums)
            if 'cm' in pl: val *= 10
            return f'{int(val)} mm' if val == int(val) else f'{val} mm'
    best, best_s = pred, 0
    pt = set(pl.split())
    for kl, kv in known.items():
        ov = len(pt & set(kl.split()))
        if ov > best_s: best_s = ov; best = kv
    return best if best_s > 0 else pred

def postprocess(pred_df, tf, fields):
    r = pred_df.copy()
    for f in fields:
        r[f] = r[f].apply(lambda x: normalize_prediction(x, f, tf))
    return r

flan_vp = postprocess(flan_vp_raw, train_flat, ALL_FIELDS)
flan_tp = postprocess(flan_tp_raw, train_flat, ALL_FIELDS)

# --- Evaluate Flan-T5 alone ---
flan_vm = evaluate_predictions(valid_flat, flan_vp, CAT_FIELDS, NUMERIC_FIELDS)
flan_tm = evaluate_predictions(test_flat, flan_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('Flan-T5 Field-by-Field — VALID', flan_vm)
print_metrics('Flan-T5 Field-by-Field — TEST', flan_tm)

# --- TF-IDF Ensemble for rare fields ---
RARE_THRESHOLD = 0.90
missing_low = {'not mentioned','not applicable','nil significant','not relevant'}
rare_fields = []
for col in CAT_FIELDS:
    frac = train_flat[col].astype(str).apply(lambda x: x.strip().lower() in missing_low).mean()
    if frac >= RARE_THRESHOLD:
        rare_fields.append(col)
print(f'\nRare fields: {len(rare_fields)} of {len(CAT_FIELDS)}')

tfidf_rare = {}
for col in rare_fields:
    y = train_flat[col].astype(str)
    if y.nunique() < 2:
        tfidf_rare[col] = y.iloc[0]
    else:
        clf = LogisticRegression(max_iter=3000, class_weight='balanced', C=1.0)
        clf.fit(X_tr, y)
        tfidf_rare[col] = clf

def ensemble(neural_pred, tfidf_models, X_sp, rf):
    r = neural_pred.copy()
    for col in rf:
        m = tfidf_models[col]
        r[col] = m if isinstance(m, str) else m.predict(X_sp)
    return r

ens_vp = ensemble(flan_vp, tfidf_rare, X_va, rare_fields)
ens_tp = ensemble(flan_tp, tfidf_rare, X_te, rare_fields)

ens_vm = evaluate_predictions(valid_flat, ens_vp, CAT_FIELDS, NUMERIC_FIELDS)
ens_tm = evaluate_predictions(test_flat, ens_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('ENSEMBLE — VALID', ens_vm)
print_metrics('ENSEMBLE — TEST', ens_tm)


Flan-T5 Field-by-Field — VALID
  leaf_avg_cat_accuracy: 0.4231707317073171
  leaf_avg_macro_f1: 0.22637218442135806
  micro_cat_accuracy: 0.42317073170731706
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Flan-T5 Field-by-Field — TEST
  leaf_avg_cat_accuracy: 0.4347560975609756
  leaf_avg_macro_f1: 0.21466459009224892
  micro_cat_accuracy: 0.4347560975609756
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Rare fields: 8 of 41

ENSEMBLE — VALID
  leaf_avg_cat_accuracy: 0.5280487804878049
  leaf_avg_macro_f1: 0.338199595350181
  micro_cat_accuracy: 0.5280487804878049
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

ENSEMBLE — TEST
  leaf_avg_cat_accuracy: 0.5359756097560976
  leaf_avg_macro_f1: 0.3037616452818985
  micro_cat_accuracy: 0.5359756097560976
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan


## Step 10: Error Analysis — Per-Field Accuracy Breakdown

This is a crucial diagnostic cell. We compute accuracy for each of the 54 fields individually and sort from worst to best, then inspect the **specific errors** (true vs. predicted values) for the 10 worst fields.

This error analysis directly informed the next three improvement iterations (extended training, better post-processing, and smart ensembling) by revealing:
- Fields where the model outputs complete nonsense (undertrained)
- Fields with systematic format errors (post-processing bugs)
- Fields where TF-IDF actually outperforms the neural model

The cell also saves all predictions and metrics to disk for later analysis.

In [11]:
# --- Per-field accuracy ---
def per_field_accuracy(yt_df, yp_df, fields):
    rows = []
    for col in fields:
        yt = yt_df[col].astype(str).str.strip().str.lower()
        yp = yp_df[col].astype(str).str.strip().str.lower()
        acc = (yt == yp).mean()
        rows.append({'field': col, 'accuracy': round(acc, 3), 'n_errors': int((yt != yp).sum())})
    return pd.DataFrame(rows).sort_values('accuracy')

err_df = per_field_accuracy(valid_flat, ens_vp, ALL_FIELDS)
print('=== Per-field accuracy (worst first) ===')
print(err_df.head(20).to_string(index=False))
n100 = (err_df['accuracy'] == 1.0).sum()
n90 = (err_df['accuracy'] >= 0.9).sum()
print(f'\nFields at 100%: {n100}/{len(ALL_FIELDS)}')
print(f'Fields at >=90%: {n90}/{len(ALL_FIELDS)}')
print(f'Average: {err_df["accuracy"].mean():.3f}')

# --- Show actual errors ---
print('\n=== Specific errors (worst 10 fields) ===')
for field in err_df.head(10)['field'].tolist():
    yt = valid_flat[field].astype(str).tolist()
    yp = ens_vp[field].astype(str).tolist()
    mm = [(t, p) for t, p in zip(yt, yp) if t.strip().lower() != p.strip().lower()]
    if mm:
        print(f'\n{field} ({len(mm)} errors):')
        for t, p in mm[:3]:
            print(f'  TRUE: {t!r:40s} PRED: {p!r}')

# --- Final comparison ---
def fmt(name, split, m):
    return {'Model': name, 'Split': split,
            'Cat Acc': round(m.get('leaf_avg_cat_accuracy', 0) or 0, 4),
            'Macro F1': round(m.get('leaf_avg_macro_f1', 0) or 0, 4),
            'Micro Acc': round(m.get('micro_cat_accuracy', 0) or 0, 4),
            'Exact Match': round(m.get('record_exact_match', 0) or 0, 4)}

results = pd.DataFrame([
    fmt('Majority', 'VALID', maj_vm), fmt('Majority', 'TEST', maj_tm),
    fmt('TF-IDF', 'VALID', tfidf_vm), fmt('TF-IDF', 'TEST', tfidf_tm),
    fmt('Flan-T5', 'VALID', flan_vm), fmt('Flan-T5', 'TEST', flan_tm),
    fmt('Ensemble', 'VALID', ens_vm), fmt('Ensemble', 'TEST', ens_tm),
])
display(results)

# --- Save ---
OUT = '/content/results_improved'
os.makedirs(OUT, exist_ok=True)
ens_vp.to_csv(f'{OUT}/ensemble_valid_pred.csv', index=False)
ens_tp.to_csv(f'{OUT}/ensemble_test_pred.csv', index=False)
err_df.to_csv(f'{OUT}/per_field_accuracy.csv', index=False)
results.to_csv(f'{OUT}/comparison.csv', index=False)
print(f'\nSaved to {OUT}')

# --- Download ---
try:
    from google.colab import files
    for f in os.listdir(OUT):
        files.download(f'{OUT}/{f}')
except:
    pass

=== Per-field accuracy (worst first) ===
                                               field  accuracy  n_errors
                                             bio.age      0.00        20
                                          bio.gender      0.00        20
                mri_numeric.current_length_of_tumour      0.00        20
                                       radial_extent      0.00        20
                                             n_stage      0.00        20
                                             t_stage      0.00        20
                     mri_stage.is_post_operative_mri      0.05        19
                                                 dwi      0.05        19
           mri_stage.is_mri_report_after_neoadjuvant      0.05        19
                                      tumour_deposit      0.05        19
                                 t2_signal_intensity      0.10        18
                      mri_numeric.location_of_tumour      0.10        18
post_treat

,Model,Split,Cat Acc,Macro F1,Micro Acc,Exact Match
0,Majority,VALID,0.5963,0.3395,0.5963,0
1,Majority,TEST,0.6360,0.3066,0.6360,0
2,TF-IDF,VALID,0.7549,0.5595,0.7549,0
3,TF-IDF,TEST,0.7091,0.4707,0.7091,0
4,Flan-T5,VALID,0.4232,0.2264,0.4232,0
5,Flan-T5,TEST,0.4348,0.2147,0.4348,0
6,Ensemble,VALID,0.5280,0.3382,0.5280,0
7,Ensemble,TEST,0.5360,0.3038,0.5360,0



Saved to /content/results_improved


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## Step 11: Fix 1 — Extended Training (20 More Epochs)

The validation loss at epoch 6 (1.43) was still dropping steeply, so the model was clearly undertrained. This cell continues training for **20 additional epochs** (epochs 7–26) with:

- A slightly lower learning rate (3e-5 → reduced from 5e-5) since we're continuing from a partially-converged state
- Less layer-wise decay (`decay=0.9`) for more uniform fine-tuning
- Increased patience (5 epochs) to allow the model more time to plateau

> **Result:** Validation loss improved from 1.43 → 0.43 over the extended training, a substantial further reduction.

In [12]:
# ============================================================
# FIX 1: Continue training — the model was severely undertrained
# Val loss was still dropping steeply (5.0 → 1.4, no plateau).
# We need 20+ more epochs.
# ============================================================

# Reset optimizer with higher LR for continued training
MORE_EPOCHS = 20
LR2 = 3e-5  # slightly lower since we're continuing

optimizer2 = get_optimizer(model, LR2, decay=0.9)  # less decay = more uniform LR
total_steps2 = len(train_loader) * MORE_EPOCHS
scheduler2 = get_linear_schedule_with_warmup(optimizer2, int(0.03 * total_steps2), total_steps2)

best_val_loss2 = best_val_loss  # start from previous best
patience_ctr2 = 0
history2 = list(history)  # continue from previous

print(f'Continuing training for {MORE_EPOCHS} more epochs ({total_steps2} steps)...')
print(f'Starting from val_loss = {best_val_loss2:.4f}\n')

for epoch in range(7, 7 + MORE_EPOCHS):
    model.train()
    total_loss = 0
    optimizer2.zero_grad()
    pbar = tqdm(train_loader, desc=f'Epoch {epoch}/{6+MORE_EPOCHS}')
    for step, batch in enumerate(pbar):
        batch = {k: v.to(device) for k, v in batch.items()}
        out = model(**batch)
        loss = out.loss / ACCUM_STEPS
        loss.backward()
        if (step + 1) % ACCUM_STEPS == 0 or (step + 1) == len(train_loader):
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer2.step(); scheduler2.step(); optimizer2.zero_grad()
        total_loss += out.loss.item()
        pbar.set_postfix(loss=f'{out.loss.item():.4f}')
    avg_train = total_loss / len(train_loader)

    model.eval()
    val_loss = 0
    with torch.no_grad():
        for batch in valid_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            val_loss += model(**batch).loss.item()
    avg_val = val_loss / len(valid_loader)
    history2.append({'epoch': epoch, 'train_loss': avg_train, 'val_loss': avg_val})
    print(f'Epoch {epoch} | Train: {avg_train:.4f} | Val: {avg_val:.4f}')

    if avg_val < best_val_loss2:
        best_val_loss2 = avg_val
        best_state = copy.deepcopy(model.state_dict())
        patience_ctr2 = 0
        torch.save(best_state, '/content/best_flan_t5_v2.pt')
        print('  -> Saved best')
    else:
        patience_ctr2 += 1
        print(f'  -> No improvement ({patience_ctr2}/5)')
        if patience_ctr2 >= 5:
            print('Early stopping.'); break

model.load_state_dict(best_state)
print(f'\nBest model loaded. Final val_loss: {best_val_loss2:.4f}')
pd.DataFrame(history2)

Continuing training for 20 more epochs (8780 steps)...
Starting from val_loss = 1.4336



Epoch 7/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 7 | Train: 1.7956 | Val: 1.3501
  -> Saved best


Epoch 8/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 8 | Train: 1.6078 | Val: 1.1811
  -> Saved best


Epoch 9/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 9 | Train: 1.4139 | Val: 1.0431
  -> Saved best


Epoch 10/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 10 | Train: 1.2522 | Val: 0.9405
  -> Saved best


Epoch 11/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 11 | Train: 1.1226 | Val: 0.8508
  -> Saved best


Epoch 12/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 12 | Train: 1.0123 | Val: 0.7852
  -> Saved best


Epoch 13/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 13 | Train: 0.9244 | Val: 0.7274
  -> Saved best


Epoch 14/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 14 | Train: 0.8545 | Val: 0.6740
  -> Saved best


Epoch 15/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 15 | Train: 0.7931 | Val: 0.6415
  -> Saved best


Epoch 16/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 16 | Train: 0.7428 | Val: 0.6096
  -> Saved best


Epoch 17/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 17 | Train: 0.7028 | Val: 0.5804
  -> Saved best


Epoch 18/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 18 | Train: 0.6580 | Val: 0.5507
  -> Saved best


Epoch 19/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 19 | Train: 0.6277 | Val: 0.5434
  -> Saved best


Epoch 20/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 20 | Train: 0.5947 | Val: 0.5224
  -> Saved best


Epoch 21/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 21 | Train: 0.5674 | Val: 0.4925
  -> Saved best


Epoch 22/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 22 | Train: 0.5417 | Val: 0.4911
  -> Saved best


Epoch 23/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 23 | Train: 0.5226 | Val: 0.4700
  -> Saved best


Epoch 24/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 24 | Train: 0.4980 | Val: 0.4603
  -> Saved best


Epoch 25/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 25 | Train: 0.4872 | Val: 0.4419
  -> Saved best


Epoch 26/26:   0%|          | 0/439 [00:00<?, ?it/s]

Epoch 26 | Train: 0.4701 | Val: 0.4331
  -> Saved best

Best model loaded. Final val_loss: 0.4331


,epoch,train_loss,val_loss
0,1,7.918474,5.012761
1,2,4.929698,3.392591
2,3,3.646989,2.548921
3,4,2.859876,2.029419
4,5,2.328229,1.675726
5,6,1.972488,1.433626
6,7,1.795648,1.350079
7,8,1.607759,1.181134
8,9,1.413937,1.043146
9,10,1.252247,0.940536


## Step 12: Fix 2 — Improved Post-Processing (v2)

Error analysis from Step 10 revealed several systematic bugs in the original post-processor:

| Problem | Root Cause | Fix |
|---------|-----------|-----|
| `bio.age: "57"` → `"0 mm"` | Age field incorrectly treated as mm measurement | Added special handling for `bio.age` — extract integer, skip `mm` suffix |
| `n_stage: "Not Mentiond"` | Model typo not caught by normaliser | Added typo map for common model misspellings |
| `t_stage: "Nil Significant"` | Wrong category entirely | Added known-label-set matching for staging fields |
| `mr_trg` not parsing | Format variants like `"TRG 3"` vs `"MR TRG 3"` | Added regex-based extraction for TRG grade |

After re-running inference with the better-trained model and applying the improved post-processor, the ensemble is rebuilt and re-evaluated.

In [13]:
# ============================================================
# FIX 2: Better post-processing
# Problems found in the error analysis:
#   - bio.age: "57" was being converted to "0 mm" (numeric field treated as mm)
#   - n_stage: model outputs "Not Mentiond" (typo) — not caught by normalizer
#   - t_stage: outputs "Nil Significant" — wrong category entirely
#   - gender: outputs "Not Mentioned" — model didn't learn to extract it
# ============================================================

def normalize_prediction_v2(pred_str, field, tf):
    """Improved post-processor with field-type awareness."""
    pred = str(pred_str).strip()
    pl = pred.lower().strip()

    # Fix common typos/variants the model generates
    typo_map = {
        'not mentiond': 'not mentioned',
        'not mentioneds': 'not mentioned',
        'not mention': 'not mentioned',
        'notmentioned': 'not mentioned',
        'not aplicable': 'not applicable',
        'nil signficant': 'nil significant',
        'nil significan': 'nil significant',
        'nill significant': 'nil significant',
    }
    if pl in typo_map:
        pl = typo_map[pl]

    # Standard missing markers
    mm = {
        'not mentioned':'Not Mentioned', 'not applicable':'Not Applicable',
        'not relevant':'Not Relevant', 'nil significant':'Nil Significant',
        'nil':'Nil Significant', 'none':'Not Mentioned', 'n/a':'Not Applicable',
        'na':'Not Applicable', 'unknown':'Not Mentioned',
        'no':'No', 'yes':'Yes', 'male':'Male', 'female':'Female',
    }
    if pl in mm:
        return mm[pl]

    # --- SPECIAL HANDLING: bio.age ---
    # Age is numeric but should NOT have "mm" appended
    if field == 'bio.age':
        nums = re.findall(r'\d+', pred)
        if nums:
            age = int(nums[0])
            if 1 <= age <= 120:
                return str(age)
        # Try to find age in the prediction text
        return pred

    # --- SPECIAL HANDLING: staging fields ---
    # T stage, N stage, M stage, MR TRG have known label sets
    if field == 't_stage':
        t_stages = ['T0','T1','T2','T3a','T3b','T3c','T3d','T4a','T4b']
        for ts in t_stages:
            if ts.lower() in pl or pl == ts.lower():
                return ts
        # Check if it contains a T followed by number
        t_match = re.search(r't\s*(\d[a-d]?)', pl, re.IGNORECASE)
        if t_match:
            return 'T' + t_match.group(1)

    if field == 'n_stage':
        n_stages = ['N0','N1','N1a','N1b','N1c','N2','N2a','N2b']
        for ns in n_stages:
            if ns.lower() in pl:
                return ns
        n_match = re.search(r'n\s*(\d[a-c]?)', pl, re.IGNORECASE)
        if n_match:
            return 'N' + n_match.group(1)

    if field == 'm_stage':
        if 'm1' in pl: return 'M1'
        if 'm0' in pl: return 'M0'

    if field == 'mr_trg':
        trg_match = re.search(r'(?:mr\s*)?trg\s*(\d)', pl, re.IGNORECASE)
        if trg_match:
            return f'MR TRG {trg_match.group(1)}'

    # Get known values from training data
    known = {v.strip().lower(): v for v in tf[field].astype(str).unique()}

    # Exact case-insensitive match
    if pl in known:
        return known[pl]

    # Substring match (both directions)
    for kl, kv in sorted(known.items(), key=lambda x: -len(x[0])):
        if len(kl) > 3 and (kl in pl or pl in kl):
            return kv

    # For numeric fields (except age), extract number + mm
    if field in NUMERIC_FIELDS and field != 'bio.age':
        nums = re.findall(r'\d+(?:\.\d+)?', pred)
        if nums:
            val = float(nums[0])  # take first number, not max
            if 'cm' in pl:
                val *= 10
            if val == int(val):
                return f'{int(val)} mm'
            else:
                return f'{val} mm'

    # Token overlap fallback
    best, best_s = pred, 0
    pt = set(pl.split())
    for kl, kv in known.items():
        ov = len(pt & set(kl.split()))
        if ov > best_s:
            best_s = ov
            best = kv
    return best if best_s > 0 else pred


def postprocess_v2(pred_df, tf, fields):
    r = pred_df.copy()
    for f in fields:
        r[f] = r[f].apply(lambda x: normalize_prediction_v2(x, f, tf))
    return r


# Re-run inference with the better-trained model
print('Re-predicting validation set...')
flan_vp_raw2 = predict_all_fields(model, tokenizer, valid_flat['text'].astype(str).tolist(), ALL_FIELDS)

print('Re-predicting test set...')
flan_tp_raw2 = predict_all_fields(model, tokenizer, test_flat['text'].astype(str).tolist(), ALL_FIELDS)

# Apply improved post-processing
flan_vp2 = postprocess_v2(flan_vp_raw2, train_flat, ALL_FIELDS)
flan_tp2 = postprocess_v2(flan_tp_raw2, train_flat, ALL_FIELDS)

# Evaluate
flan_vm2 = evaluate_predictions(valid_flat, flan_vp2, CAT_FIELDS, NUMERIC_FIELDS)
flan_tm2 = evaluate_predictions(test_flat, flan_tp2, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('Flan-T5 v2 (more epochs + better PP) — VALID', flan_vm2)
print_metrics('Flan-T5 v2 (more epochs + better PP) — TEST', flan_tm2)

# Rebuild ensemble with updated predictions
ens_vp2 = ensemble(flan_vp2, tfidf_rare, X_va, rare_fields)
ens_tp2 = ensemble(flan_tp2, tfidf_rare, X_te, rare_fields)

ens_vm2 = evaluate_predictions(valid_flat, ens_vp2, CAT_FIELDS, NUMERIC_FIELDS)
ens_tm2 = evaluate_predictions(test_flat, ens_tp2, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('ENSEMBLE v2 — VALID', ens_vm2)
print_metrics('ENSEMBLE v2 — TEST', ens_tm2)

Re-predicting validation set...


Predicting:   0%|          | 0/20 [00:00<?, ?it/s]

Re-predicting test set...


Predicting:   0%|          | 0/40 [00:00<?, ?it/s]


Flan-T5 v2 (more epochs + better PP) — VALID
  leaf_avg_cat_accuracy: 0.5524390243902438
  leaf_avg_macro_f1: 0.35599650106951297
  micro_cat_accuracy: 0.552439024390244
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Flan-T5 v2 (more epochs + better PP) — TEST
  leaf_avg_cat_accuracy: 0.5713414634146342
  leaf_avg_macro_f1: 0.3233696047845707
  micro_cat_accuracy: 0.5713414634146341
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

ENSEMBLE v2 — VALID
  leaf_avg_cat_accuracy: 0.6463414634146342
  leaf_avg_macro_f1: 0.4539310868089767
  micro_cat_accuracy: 0.6463414634146342
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

ENSEMBLE v2 — TEST
  leaf_avg_cat_accuracy: 0.6652439024390243
  leaf_avg_macro_f1: 0.40195423464006075
  micro_cat_accuracy: 0.6652439024390244
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan


## Step 13: Fix 3 — Smart Per-Field Ensemble

Rather than using a single model for all fields, we realised that **different models excel at different fields**. For some fields (especially rare binary ones), TF-IDF logistic regression actually outperforms the neural model.

This cell implements a **per-field model selection** strategy:
1. Compute validation accuracy for each field under both Flan-T5 and TF-IDF
2. For each field, select whichever model achieves higher validation accuracy
3. Construct the ensemble by mixing predictions from both models

The output shows the chosen model for each field and the resulting accuracy improvement.

In [14]:
# ============================================================
# FIX 3: Smart per-field ensemble
# Instead of blindly using Flan-T5 or TF-IDF, pick the BEST
# model per field based on validation accuracy.
# ============================================================

# Per-field accuracy for each model on validation
def get_per_field_acc(yt_df, yp_df, fields):
    accs = {}
    for col in fields:
        yt = yt_df[col].astype(str).str.strip().str.lower()
        yp = yp_df[col].astype(str).str.strip().str.lower()
        accs[col] = (yt == yp).mean()
    return accs

acc_flan = get_per_field_acc(valid_flat, flan_vp2, ALL_FIELDS)
acc_tfidf = get_per_field_acc(valid_flat, tfidf_vp, ALL_FIELDS)

# For each field, pick whichever model is better on validation
smart_valid_pred = pd.DataFrame(index=valid_flat.index)
smart_test_pred = pd.DataFrame(index=test_flat.index)
model_choice = {}

for col in ALL_FIELDS:
    flan_acc = acc_flan.get(col, 0)
    tfidf_acc = acc_tfidf.get(col, 0)

    if tfidf_acc >= flan_acc:
        smart_valid_pred[col] = tfidf_vp[col]
        smart_test_pred[col] = tfidf_tp[col]
        model_choice[col] = f'TF-IDF ({tfidf_acc:.0%})'
    else:
        smart_valid_pred[col] = flan_vp2[col]
        smart_test_pred[col] = flan_tp2[col]
        model_choice[col] = f'Flan-T5 ({flan_acc:.0%})'

# Show which model was chosen per field
print('=== Model selection per field ===')
flan_count = sum(1 for v in model_choice.values() if 'Flan' in v)
tfidf_count = len(model_choice) - flan_count
print(f'Flan-T5 chosen: {flan_count}, TF-IDF chosen: {tfidf_count}\n')

for col in ALL_FIELDS:
    fa = acc_flan.get(col, 0)
    ta = acc_tfidf.get(col, 0)
    chosen = model_choice[col]
    marker = '  <<<' if fa > ta else ''
    print(f'  {col:60s} TF-IDF={ta:.0%}  Flan={fa:.0%}  -> {chosen}{marker}')

# Evaluate smart ensemble
smart_vm = evaluate_predictions(valid_flat, smart_valid_pred, CAT_FIELDS, NUMERIC_FIELDS)
smart_tm = evaluate_predictions(test_flat, smart_test_pred, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('\nSMART ENSEMBLE — VALID', smart_vm)
print_metrics('SMART ENSEMBLE — TEST', smart_tm)

# Updated comparison table
results2 = pd.DataFrame([
    fmt('Majority', 'VALID', maj_vm), fmt('Majority', 'TEST', maj_tm),
    fmt('TF-IDF', 'VALID', tfidf_vm), fmt('TF-IDF', 'TEST', tfidf_tm),
    fmt('Flan-T5 v2', 'VALID', flan_vm2), fmt('Flan-T5 v2', 'TEST', flan_tm2),
    fmt('Smart Ensemble', 'VALID', smart_vm), fmt('Smart Ensemble', 'TEST', smart_tm),
])
display(results2)

=== Model selection per field ===
Flan-T5 chosen: 19, TF-IDF chosen: 35

  report_type                                                  TF-IDF=100%  Flan=100%  -> TF-IDF (100%)
  bio.age                                                      TF-IDF=0%  Flan=65%  -> Flan-T5 (65%)  <<<
  bio.gender                                                   TF-IDF=95%  Flan=65%  -> TF-IDF (95%)
  mri_numeric.current_length_of_tumour                         TF-IDF=0%  Flan=70%  -> Flan-T5 (70%)  <<<
  mri_numeric.location_of_tumour                               TF-IDF=55%  Flan=75%  -> Flan-T5 (75%)  <<<
  mri_numeric.distance_from_anal_verge                         TF-IDF=70%  Flan=30%  -> TF-IDF (70%)
  mri_numeric.distance_from_anorectal_junction                 TF-IDF=10%  Flan=65%  -> Flan-T5 (65%)  <<<
  mri_numeric.extramural_spread_size                           TF-IDF=10%  Flan=55%  -> Flan-T5 (55%)  <<<
  mri_numeric.mr_crm_distance                                  TF-IDF=0%  Flan=80%  -> F

,Model,Split,Cat Acc,Macro F1,Micro Acc,Exact Match
0,Majority,VALID,0.5963,0.3395,0.5963,0
1,Majority,TEST,0.6360,0.3066,0.6360,0
2,TF-IDF,VALID,0.7549,0.5595,0.7549,0
3,TF-IDF,TEST,0.7091,0.4707,0.7091,0
4,Flan-T5 v2,VALID,0.5524,0.3560,0.5524,0
5,Flan-T5 v2,TEST,0.5713,0.3234,0.5713,0
6,Smart Ensemble,VALID,0.7744,0.5785,0.7744,0
7,Smart Ensemble,TEST,0.7512,0.4958,0.7512,0


## Step 14: Scale Up — Fine-Tune Flan-T5-Large (780M Parameters)

Since Flan-T5-Base plateaued, we try the 3× larger `google/flan-t5-large` (780M parameters). Key changes:

| Parameter | Base | Large |
|-----------|------|-------|
| Parameters | 248M | 780M |
| Batch size | 8 | 4 (GPU memory constrained) |
| Max input length | 512 | 768 (less truncation) |
| Gradient accumulation | 2 | 4 (effective batch = 16) |
| Learning rate | 5e-5 | 2e-5 (lower for larger model) |
| Epochs | 6+20 | 15 |

The larger model has more capacity to learn the nuances of medical text but is at higher risk of overfitting on just 65 training reports. We use a simpler optimiser (AdamW without layer-wise decay) since the larger model has enough capacity across all layers.

> **Note:** This requires an A100 GPU. The cell first frees memory from the Base model before loading Large.

In [15]:
# ============================================================
# EXPERIMENT: Flan-T5-Large (780M params)
# Only run this if flan-t5-base didn't hit your target.
# Needs A100 GPU. Reduce BATCH_SIZE to 4 if OOM.
# ============================================================

# Free memory from previous model
del model, optimizer, optimizer2, scheduler, scheduler2
torch.cuda.empty_cache()
import gc; gc.collect()

MODEL_NAME_L = 'google/flan-t5-large'
BATCH_SIZE_L = 4
MAX_INPUT_L = 768  # longer input to avoid truncation
EPOCHS_L = 15
LR_L = 2e-5
ACCUM_L = 4  # effective batch = 16

print(f'Loading {MODEL_NAME_L}...')
tokenizer_l = AutoTokenizer.from_pretrained(MODEL_NAME_L)
model_l = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME_L).to(device)
print(f'Params: {sum(p.numel() for p in model_l.parameters()):,}')

# Rebuild datasets with longer input
train_ds_l = FieldByFieldDataset(train_flat, ALL_FIELDS, tokenizer_l, MAX_INPUT_L, MAX_TARGET_LEN)
valid_ds_l = FieldByFieldDataset(valid_flat, ALL_FIELDS, tokenizer_l, MAX_INPUT_L, MAX_TARGET_LEN)

train_loader_l = DataLoader(train_ds_l, batch_size=BATCH_SIZE_L, shuffle=True, num_workers=2, pin_memory=True)
valid_loader_l = DataLoader(valid_ds_l, batch_size=BATCH_SIZE_L, shuffle=False, num_workers=2, pin_memory=True)

# Simple AdamW (skip layerwise for simplicity, large model has enough capacity)
optimizer_l = torch.optim.AdamW(model_l.parameters(), lr=LR_L, weight_decay=0.01)
total_steps_l = len(train_loader_l) * EPOCHS_L
scheduler_l = get_linear_schedule_with_warmup(optimizer_l, int(0.06 * total_steps_l), total_steps_l)

best_vl_l = float('inf')
best_state_l = None
patience_l = 0
history_l = []

print(f'\nTraining: {total_steps_l} steps, {EPOCHS_L} epochs\n')

for epoch in range(1, EPOCHS_L + 1):
    model_l.train()
    total_loss = 0
    optimizer_l.zero_grad()
    pbar = tqdm(train_loader_l, desc=f'Epoch {epoch}/{EPOCHS_L}')
    for step, batch in enumerate(pbar):
        batch = {k: v.to(device) for k, v in batch.items()}
        out = model_l(**batch)
        loss = out.loss / ACCUM_L
        loss.backward()
        if (step + 1) % ACCUM_L == 0 or (step + 1) == len(train_loader_l):
            torch.nn.utils.clip_grad_norm_(model_l.parameters(), 1.0)
            optimizer_l.step(); scheduler_l.step(); optimizer_l.zero_grad()
        total_loss += out.loss.item()
        pbar.set_postfix(loss=f'{out.loss.item():.4f}')
    avg_train = total_loss / len(train_loader_l)

    model_l.eval()
    val_loss = 0
    with torch.no_grad():
        for batch in valid_loader_l:
            batch = {k: v.to(device) for k, v in batch.items()}
            val_loss += model_l(**batch).loss.item()
    avg_val = val_loss / len(valid_loader_l)
    history_l.append({'epoch': epoch, 'train_loss': avg_train, 'val_loss': avg_val})
    print(f'Epoch {epoch} | Train: {avg_train:.4f} | Val: {avg_val:.4f}')

    if avg_val < best_vl_l:
        best_vl_l = avg_val
        best_state_l = copy.deepcopy(model_l.state_dict())
        patience_l = 0
        torch.save(best_state_l, '/content/best_flan_t5_large.pt')
        print('  -> Saved best')
    else:
        patience_l += 1
        print(f'  -> No improvement ({patience_l}/4)')
        if patience_l >= 4:
            print('Early stopping.'); break

model_l.load_state_dict(best_state_l)
print(f'\nBest model loaded. Val loss: {best_vl_l:.4f}')
pd.DataFrame(history_l)

Loading google/flan-t5-large...


config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/3.13G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/558 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning


generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Params: 783,150,080

Training: 13170 steps, 15 epochs



Epoch 1/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 1 | Train: 9.0510 | Val: 7.1637
  -> Saved best


Epoch 2/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 2 | Train: 7.2539 | Val: 4.7592
  -> Saved best


Epoch 3/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 3 | Train: 5.4463 | Val: 3.3191
  -> Saved best


Epoch 4/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 4 | Train: 3.7615 | Val: 2.1518
  -> Saved best


Epoch 5/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 5 | Train: 2.5807 | Val: 1.5306
  -> Saved best


Epoch 6/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 6 | Train: 1.9159 | Val: 1.1720
  -> Saved best


Epoch 7/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 7 | Train: 1.4965 | Val: 0.9523
  -> Saved best


Epoch 8/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 8 | Train: 1.2302 | Val: 0.7992
  -> Saved best


Epoch 9/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 9 | Train: 1.0357 | Val: 0.6820
  -> Saved best


Epoch 10/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 10 | Train: 0.8891 | Val: 0.6019
  -> Saved best


Epoch 11/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 11 | Train: 0.7814 | Val: 0.5297
  -> Saved best


Epoch 12/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 12 | Train: 0.6899 | Val: 0.4851
  -> Saved best


Epoch 13/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 13 | Train: 0.6240 | Val: 0.4500
  -> Saved best


Epoch 14/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 14 | Train: 0.5695 | Val: 0.4284
  -> Saved best


Epoch 15/15:   0%|          | 0/878 [00:00<?, ?it/s]

Epoch 15 | Train: 0.5237 | Val: 0.3945
  -> Saved best

Best model loaded. Val loss: 0.3945


,epoch,train_loss,val_loss
0,1,9.051045,7.163703
1,2,7.253931,4.759180
2,3,5.446255,3.319150
3,4,3.761483,2.151848
4,5,2.580652,1.530630
5,6,1.915949,1.172045
6,7,1.496483,0.952325
7,8,1.230230,0.799179
8,9,1.035687,0.681965
9,10,0.889116,0.601850


## Step 15: Evaluate Flan-T5-Large & Build Best-of-3 Ensemble

After training Flan-T5-Large, we:

1. **Run inference** on validation and test sets using the Large model
2. **Build a best-of-3 ensemble** that selects, for each field, whichever model (TF-IDF, Flan-T5-Base, or Flan-T5-Large) achieves the highest validation accuracy
3. **Run per-field error analysis** to see where the Large model improves or regresses vs. Base
4. **Produce the final comparison table** across all approaches so far

This best-of-3 ensemble represents the upper bound of what our fine-tuning approach can achieve.

In [16]:
# ============================================================
# Evaluate Flan-T5-Large
# ============================================================

print('Predicting with Flan-T5-Large...')
flan_l_vp_raw = predict_all_fields(model_l, tokenizer_l, valid_flat['text'].astype(str).tolist(),
                                    ALL_FIELDS, max_input=MAX_INPUT_L)
flan_l_tp_raw = predict_all_fields(model_l, tokenizer_l, test_flat['text'].astype(str).tolist(),
                                    ALL_FIELDS, max_input=MAX_INPUT_L)

flan_l_vp = postprocess_v2(flan_l_vp_raw, train_flat, ALL_FIELDS)
flan_l_tp = postprocess_v2(flan_l_tp_raw, train_flat, ALL_FIELDS)

flan_l_vm = evaluate_predictions(valid_flat, flan_l_vp, CAT_FIELDS, NUMERIC_FIELDS)
flan_l_tm = evaluate_predictions(test_flat, flan_l_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('Flan-T5-Large — VALID', flan_l_vm)
print_metrics('Flan-T5-Large — TEST', flan_l_tm)

# Smart ensemble with large model
acc_flan_l = get_per_field_acc(valid_flat, flan_l_vp, ALL_FIELDS)

smart2_vp = pd.DataFrame(index=valid_flat.index)
smart2_tp = pd.DataFrame(index=test_flat.index)

for col in ALL_FIELDS:
    # Pick best among: TF-IDF, Flan-base-v2, Flan-large
    candidates = {
        'tfidf': (acc_tfidf.get(col, 0), tfidf_vp[col], tfidf_tp[col]),
        'flan_base': (acc_flan.get(col, 0), flan_vp2[col], flan_tp2[col]),
        'flan_large': (acc_flan_l.get(col, 0), flan_l_vp[col], flan_l_tp[col]),
    }
    best_name = max(candidates, key=lambda k: candidates[k][0])
    _, vp_col, tp_col = candidates[best_name]
    smart2_vp[col] = vp_col
    smart2_tp[col] = tp_col

smart2_vm = evaluate_predictions(valid_flat, smart2_vp, CAT_FIELDS, NUMERIC_FIELDS)
smart2_tm = evaluate_predictions(test_flat, smart2_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('BEST-OF-3 ENSEMBLE — VALID', smart2_vm)
print_metrics('BEST-OF-3 ENSEMBLE — TEST', smart2_tm)

# Per-field error analysis for Large model
err_l = per_field_accuracy(valid_flat, flan_l_vp, ALL_FIELDS)
print('\n=== Flan-T5-Large per-field accuracy (worst first) ===')
print(err_l.head(15).to_string(index=False))
n100 = (err_l['accuracy'] == 1.0).sum()
n90 = (err_l['accuracy'] >= 0.9).sum()
print(f'\nFields at 100%: {n100}/{len(ALL_FIELDS)}')
print(f'Fields at >=90%: {n90}/{len(ALL_FIELDS)}')
print(f'Average: {err_l["accuracy"].mean():.3f}')

# Final comparison
print('\n\n=== FINAL COMPARISON ===')
final = pd.DataFrame([
    fmt('Majority', 'VALID', maj_vm), fmt('Majority', 'TEST', maj_tm),
    fmt('TF-IDF', 'VALID', tfidf_vm), fmt('TF-IDF', 'TEST', tfidf_tm),
    fmt('Flan-T5-Base v2', 'VALID', flan_vm2), fmt('Flan-T5-Base v2', 'TEST', flan_tm2),
    fmt('Flan-T5-Large', 'VALID', flan_l_vm), fmt('Flan-T5-Large', 'TEST', flan_l_tm),
    fmt('Best-of-3', 'VALID', smart2_vm), fmt('Best-of-3', 'TEST', smart2_tm),
])
display(final)

# Save everything
OUT = '/content/results_v2'
os.makedirs(OUT, exist_ok=True)
smart2_vp.to_csv(f'{OUT}/best_ensemble_valid.csv', index=False)
smart2_tp.to_csv(f'{OUT}/best_ensemble_test.csv', index=False)
flan_l_vp.to_csv(f'{OUT}/flan_large_valid.csv', index=False)
flan_l_tp.to_csv(f'{OUT}/flan_large_test.csv', index=False)
err_l.to_csv(f'{OUT}/per_field_accuracy_large.csv', index=False)
final.to_csv(f'{OUT}/final_comparison.csv', index=False)
print(f'\nSaved to {OUT}')

try:
    from google.colab import files
    for f in os.listdir(OUT):
        files.download(f'{OUT}/{f}')
except:
    pass

Predicting with Flan-T5-Large...


Predicting:   0%|          | 0/20 [00:00<?, ?it/s]

Predicting:   0%|          | 0/40 [00:00<?, ?it/s]


Flan-T5-Large — VALID
  leaf_avg_cat_accuracy: 0.6280487804878049
  leaf_avg_macro_f1: 0.45257817865323746
  micro_cat_accuracy: 0.6280487804878049
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Flan-T5-Large — TEST
  leaf_avg_cat_accuracy: 0.6335365853658537
  leaf_avg_macro_f1: 0.4303437422194658
  micro_cat_accuracy: 0.6335365853658537
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

BEST-OF-3 ENSEMBLE — VALID
  leaf_avg_cat_accuracy: 0.8146341463414634
  leaf_avg_macro_f1: 0.6297625322387252
  micro_cat_accuracy: 0.8146341463414634
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

BEST-OF-3 ENSEMBLE — TEST
  leaf_avg_cat_accuracy: 0.7847560975609755
  leaf_avg_macro_f1: 0.5353305494065891
  micro_cat_accuracy: 0.7847560975609756
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

=== Flan-T5-Large per-field accuracy (worst first) ===
                                                     field 

,Model,Split,Cat Acc,Macro F1,Micro Acc,Exact Match
0,Majority,VALID,0.5963,0.3395,0.5963,0
1,Majority,TEST,0.6360,0.3066,0.6360,0
2,TF-IDF,VALID,0.7549,0.5595,0.7549,0
3,TF-IDF,TEST,0.7091,0.4707,0.7091,0
4,Flan-T5-Base v2,VALID,0.5524,0.3560,0.5524,0
5,Flan-T5-Base v2,TEST,0.5713,0.3234,0.5713,0
6,Flan-T5-Large,VALID,0.6280,0.4526,0.6280,0
7,Flan-T5-Large,TEST,0.6335,0.4303,0.6335,0
8,Best-of-3,VALID,0.8146,0.6298,0.8146,0
9,Best-of-3,TEST,0.7848,0.5353,0.7848,0



Saved to /content/results_v2


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## Step 16: Fix 4 — Rule-Based Constraint Layer

Fine-tuned models at this scale cannot learn all the **logical constraints** that a domain expert would enforce. This cell applies 12 hand-crafted rules as a post-processing layer on top of the best-of-3 ensemble:

| Rule | Fields Affected | Logic |
|------|----------------|-------|
| Gender regex extraction | `bio.gender` | Extract gender directly from report text using keyword patterns (more reliable than the model) |
| Gender gating | 5 gender-specific fields | Male → female anatomy = "Not Applicable" and vice versa |
| Training-prior correction | 20 fields | If "Not Mentioned" is rare in training (<10%) but the model predicts it, replace with the training-mode value |
| T4b gating | T4b adjacency fields | If T-stage ≠ T4b, suspect "Yes" predictions for T4b involvement → "No" |
| is_t4a consistency | `is_t4a` | Must agree with `t_stage` |
| MR TRG gating | `mr_trg` | Only applies to post-treatment/restaging MRIs |
| Post-treatment gating | 4 post-tx fields | Not applicable for first-time MRIs |
| Age regex extraction | `bio.age` | Extract age directly from report text |
| MRI stage constraints | `is_first_mri_report` | If restaging = Yes → first = No |
| Numeric clamping | Distance fields | Flag values >200mm as unreasonable |

> **Result:** The rules fixed the 4 fields that had 0% accuracy (levator_ani, obturator muscles, piriformis) but only added ~0.13% overall because most errors are content-comprehension failures that rules cannot address.

In [17]:
# ============================================================
# FIX 4: Rule-Based Constraint Layer
# Applies domain knowledge ON TOP of the best-of-3 ensemble.
#
# Key insight: many errors come from the model predicting a
# plausible-sounding default ("Not Mentioned", "No") when the
# schema actually expects a different label. Rules fix these
# by using (a) training-data distributions, (b) regex extraction
# from the report text, and (c) logical cross-field constraints.
#
# This cell expects all variables from cells 0–14 to be available:
#   smart2_vp, smart2_tp, flan_l_vp, flan_l_tp, flan_vp2, flan_tp2,
#   tfidf_vp, tfidf_tp, valid_flat, test_flat, train_flat,
#   ALL_FIELDS, CAT_FIELDS, NUMERIC_FIELDS,
#   evaluate_predictions, print_metrics, per_field_accuracy, fmt, etc.
# ============================================================

import re
import numpy as np
import pandas as pd
from copy import deepcopy


# ------------------------------------------------------------------
# STEP 0: Snapshot the BEFORE state so we can measure improvement
# ------------------------------------------------------------------
print("=" * 70)
print("RULE-BASED CONSTRAINT LAYER")
print("=" * 70)

before_vm = evaluate_predictions(valid_flat, smart2_vp, CAT_FIELDS, NUMERIC_FIELDS)
before_tm = evaluate_predictions(test_flat, smart2_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics("\n[BEFORE rules] Best-of-3 — VALID", before_vm)
print_metrics("[BEFORE rules] Best-of-3 — TEST", before_tm)


# ------------------------------------------------------------------
# STEP 1: Learn training-data priors for each field
# ------------------------------------------------------------------
# For every field, compute the value distribution in train_flat.
# This tells us what the "normal" label is.
# ------------------------------------------------------------------
train_distributions = {}
for col in ALL_FIELDS:
    vc = train_flat[col].astype(str).str.strip().str.lower().value_counts(normalize=True)
    train_distributions[col] = vc

# Identify fields where "not mentioned" almost NEVER appears in training
# but the models keep predicting it — a strong signal the default is wrong.
not_mentioned_rare_fields = {}
for col in ALL_FIELDS:
    dist = train_distributions[col]
    nm_frac = dist.get('not mentioned', 0)
    # If "not mentioned" is <10% in training, it's likely wrong when predicted
    if nm_frac < 0.10:
        # The correct default is the most common training value
        not_mentioned_rare_fields[col] = dist.index[0]  # most common label

print(f"\nFields where 'Not Mentioned' is rare in training (<10%): "
      f"{len(not_mentioned_rare_fields)}")
for col, default in sorted(not_mentioned_rare_fields.items()):
    nm_frac = train_distributions[col].get('not mentioned', 0)
    print(f"  {col:60s} -> default='{default}' (NM={nm_frac:.0%} in train)")


# ------------------------------------------------------------------
# STEP 2: Build regex-based extractors from report text
# ------------------------------------------------------------------

def extract_gender_from_text(report_text):
    """
    Reliably extract patient gender from the MRI report text.
    Much more accurate than letting the model guess.
    """
    text = str(report_text).lower()

    # Common patterns in Indian MRI reports
    # Direct mentions: "male patient", "female", "mr./mrs.", "he/she"
    male_patterns = [
        r'\bmale\b', r'\b(?:mr|sri|shri)\.?\s', r'\bman\b',
        r'\bhis\b', r'\bhe\b',
        # Gender-specific anatomy mentioned as present (not "not applicable")
        r'\bprostat(?:e|ic)\b',
        r'\bseminal\s+vesicle',
    ]
    female_patterns = [
        r'\bfemale\b', r'\b(?:mrs|ms|smt)\.?\s', r'\bwoman\b',
        r'\bher\b', r'\bshe\b',
        # Gender-specific anatomy mentioned as present
        r'\buter(?:us|ine)\b', r'\bovari(?:es|an)\b', r'\bvagin(?:a|al)\b',
        r'\bcervix\b', r'\bcervical\b',
    ]

    male_score = sum(1 for p in male_patterns if re.search(p, text))
    female_score = sum(1 for p in female_patterns if re.search(p, text))

    if male_score > female_score:
        return 'Male'
    elif female_score > male_score:
        return 'Female'
    return None  # uncertain — don't override


def extract_age_from_text(report_text):
    """Extract age from report text using common patterns."""
    text = str(report_text)
    # Patterns: "57 year old", "age: 57", "57/M", "57/F", "aged 57"
    patterns = [
        r'(\d{1,3})\s*(?:year|yr|y)[\s\-]*(?:old|age)',
        r'(?:age|aged)\s*[:\-]?\s*(\d{1,3})',
        r'(\d{1,3})\s*/\s*[MFmf]\b',
        r'\b(\d{2})\s*(?:male|female)\b',
    ]
    for p in patterns:
        m = re.search(p, text, re.IGNORECASE)
        if m:
            age = int(m.group(1))
            if 1 <= age <= 120:
                return str(age)
    return None


def extract_t_stage_from_text(report_text):
    """Extract T-stage if clearly stated in the report."""
    text = str(report_text)
    # Look for explicit staging: "T3b", "T stage: T3b", "T-stage T3b"
    patterns = [
        r'(?:overall\s+)?(?:T|t)[\s\-]*(?:stage|staging)\s*[:\-]?\s*(T\d[a-d]?)\b',
        r'\b(T[0-4][a-d]?)\b(?!\s*(?:signal|weighted|sequence|hypo|hyper))',
    ]
    for p in patterns:
        matches = re.findall(p, text, re.IGNORECASE)
        if matches:
            # Take the last occurrence (often the conclusion)
            stage = matches[-1].upper()
            valid_stages = ['T0','T1','T2','T3','T3A','T3B','T3C','T3D','T4A','T4B']
            if stage in valid_stages:
                return stage
    return None


# ------------------------------------------------------------------
# STEP 3: Define the main rule-application function
# ------------------------------------------------------------------

def apply_rules(pred_df, source_texts, train_flat_ref):
    """
    Apply domain-knowledge rules to fix prediction errors.

    Args:
        pred_df: DataFrame of predictions (one row per report)
        source_texts: list/Series of original report texts
        train_flat_ref: training data DataFrame for distribution lookup
    Returns:
        DataFrame with corrected predictions
    """
    result = pred_df.copy()
    n = len(result)

    # Track how many corrections each rule makes
    rule_counts = {}
    def count(rule_name, mask):
        rule_counts[rule_name] = rule_counts.get(rule_name, 0) + int(mask.sum())

    # ---------------------------------------------------------------
    # RULE 1: Gender extraction from text (bypass model predictions)
    # ---------------------------------------------------------------
    for i in range(n):
        text = str(source_texts.iloc[i]) if hasattr(source_texts, 'iloc') else str(source_texts[i])
        extracted = extract_gender_from_text(text)
        if extracted is not None:
            old = result.at[result.index[i], 'bio.gender']
            if str(old).strip().lower() != extracted.lower():
                result.at[result.index[i], 'bio.gender'] = extracted

    # ---------------------------------------------------------------
    # RULE 2: Gender-gated fields
    # If Male -> female-specific fields = "Not Applicable"
    # If Female -> male-specific fields = "Not Applicable"
    # ---------------------------------------------------------------
    male_only_fields = [
        'adjacent_structures_t4b.male.prostate',
        'adjacent_structures_t4b.male.seminal_vesicles',
    ]
    female_only_fields = [
        'adjacent_structures_t4b.female.ovaries',
        'adjacent_structures_t4b.female.uterus',
        'adjacent_structures_t4b.female.vagina',
    ]

    gender = result['bio.gender'].astype(str).str.strip().str.lower()

    for col in female_only_fields:
        mask = (gender == 'male') & (result[col].astype(str).str.strip().str.lower() != 'not applicable')
        result.loc[mask, col] = 'Not Applicable'
        count('gender_gate_female_fields', mask)

    for col in male_only_fields:
        mask = (gender == 'female') & (result[col].astype(str).str.strip().str.lower() != 'not applicable')
        result.loc[mask, col] = 'Not Applicable'
        count('gender_gate_male_fields', mask)

    # ---------------------------------------------------------------
    # RULE 3: Fix "Not Mentioned" for fields where it's rare/absent
    #         in training data. Replace with the training-mode value.
    # ---------------------------------------------------------------
    for col, default_val in not_mentioned_rare_fields.items():
        # Get the properly-cased default from training data
        proper_case = train_flat_ref[col].astype(str).value_counts().index[0]
        pred_lower = result[col].astype(str).str.strip().str.lower()
        mask = (pred_lower == 'not mentioned')
        result.loc[mask, col] = proper_case
        count(f'nm_replace_{col}', mask)

    # ---------------------------------------------------------------
    # RULE 4: T4b adjacent-structure gating
    # If T-stage is NOT T4b, then T4b-specific adjacent structures
    # should default to "No" (not involved).
    # ---------------------------------------------------------------
    t4b_adj_fields = [
        'adjacent_structures_t4b.male_and_female.puborectalis',
        'adjacent_structures_t4b.male_and_female.levator_ani',
        'adjacent_structures_t4b.male_and_female.obturator_internus',
        'adjacent_structures_t4b.male_and_female.obturator_externus',
        'adjacent_structures_t4b.male_and_female.piriformis',
        'adjacent_structures_t4b.male.prostate',
        'adjacent_structures_t4b.male.seminal_vesicles',
        'adjacent_structures_t4b.female.ovaries',
        'adjacent_structures_t4b.female.uterus',
        'adjacent_structures_t4b.female.vagina',
    ]
    t4b_sphincter_fields = [
        'anal_sphincter_complex.t4b.external_sphincter',
        'anal_sphincter_complex.t4b.inter_sphincteric_plane',
        'anal_sphincter_complex.t4b.ischiorectal_foss',
        'anal_sphincter_complex.t4b.fistula_in_ano',
    ]

    t_stage_lower = result['t_stage'].astype(str).str.strip().str.lower()
    not_t4b = (t_stage_lower != 't4b')

    for col in t4b_adj_fields:
        pred_lower = result[col].astype(str).str.strip().str.lower()
        # Don't override "Not Applicable" (gender-gated) or "Yes" (explicit)
        mask = not_t4b & (pred_lower == 'yes')
        # If not T4b and model says "Yes" for T4b involvement, that's suspect
        # Only override if training data strongly disagrees
        train_yes_rate = train_distributions.get(col, pd.Series()).get('yes', 0)
        train_t4b_rate = train_distributions.get('t_stage', pd.Series()).get('t4b', 0)
        # This is a soft rule — only override if involvement is very rare
        if train_yes_rate < 0.15:
            result.loc[mask, col] = 'No'
            count('t4b_gate_adj', mask)

    # ---------------------------------------------------------------
    # RULE 5: is_t4a consistency with t_stage
    # If t_stage is explicitly T4a, is_t4a should be "Yes"
    # If t_stage is NOT T4a, is_t4a should be "No"
    # ---------------------------------------------------------------
    is_t4a = t_stage_lower == 't4a'
    is_not_t4a = ~t_stage_lower.isin(['t4a', 'not mentioned'])

    mask_should_yes = is_t4a & (result['is_t4a'].astype(str).str.strip().str.lower() != 'yes')
    result.loc[mask_should_yes, 'is_t4a'] = 'Yes'
    count('t4a_consistency_yes', mask_should_yes)

    mask_should_no = is_not_t4a & (result['is_t4a'].astype(str).str.strip().str.lower() == 'yes')
    result.loc[mask_should_no, 'is_t4a'] = 'No'
    count('t4a_consistency_no', mask_should_no)

    # ---------------------------------------------------------------
    # RULE 6: MR TRG only for post-treatment/restaging MRIs
    # If not a post-treatment MRI, MR TRG should be "Not Mentioned"
    # ---------------------------------------------------------------
    is_post_tx = result['mri_stage.is_post_treatment_mri_report'].astype(str).str.strip().str.lower()
    is_restaging = result['mri_stage.is_restaging_mri_report'].astype(str).str.strip().str.lower()
    not_post_treatment = (is_post_tx != 'yes') & (is_restaging != 'yes')

    mr_trg_lower = result['mr_trg'].astype(str).str.strip().str.lower()
    mask = not_post_treatment & (~mr_trg_lower.isin(['not mentioned', 'not applicable']))
    result.loc[mask, 'mr_trg'] = 'Not Mentioned'
    count('mr_trg_gate', mask)

    # ---------------------------------------------------------------
    # RULE 7: Post-treatment change fields — only for post-tx MRIs
    # ---------------------------------------------------------------
    post_tx_fields = [
        'post_treatment_change.is_thick_t2_hypointense_band',
        'post_treatment_change.is_thin_t2_hypointense_band',
        'post_treatment_change.is_residual_tumor_as_first_mri',
        'post_treatment_change.is_mucin_reaction_t2_hyper_hypo_post_treatment',
    ]
    # If it's a FIRST MRI (not post-treatment), post-tx fields = "Not Mentioned"
    is_first = result['mri_stage.is_first_mri_report'].astype(str).str.strip().str.lower()
    clearly_first = (is_first == 'yes') & (is_post_tx != 'yes')

    for col in post_tx_fields:
        pred_lower = result[col].astype(str).str.strip().str.lower()
        mask = clearly_first & (~pred_lower.isin(['not mentioned', 'not applicable']))
        result.loc[mask, col] = 'Not Mentioned'
        count('post_tx_gate', mask)

    # ---------------------------------------------------------------
    # RULE 8: Age extraction from text (more reliable than model)
    # ---------------------------------------------------------------
    for i in range(n):
        text = str(source_texts.iloc[i]) if hasattr(source_texts, 'iloc') else str(source_texts[i])
        extracted_age = extract_age_from_text(text)
        if extracted_age is not None:
            current = str(result.at[result.index[i], 'bio.age']).strip()
            # Only override if current prediction seems wrong
            curr_nums = re.findall(r'\d+', current)
            if not curr_nums or abs(int(curr_nums[0]) - int(extracted_age)) > 5:
                result.at[result.index[i], 'bio.age'] = extracted_age

    # ---------------------------------------------------------------
    # RULE 9: report_type is always "MRI" for this dataset
    # ---------------------------------------------------------------
    mask = result['report_type'].astype(str).str.strip().str.lower() != 'mri'
    result.loc[mask, 'report_type'] = 'MRI'
    count('report_type_fix', mask)

    # ---------------------------------------------------------------
    # RULE 10: MRI stage mutual constraints
    # is_first_mri_report and is_restaging are somewhat exclusive
    # ---------------------------------------------------------------
    # If is_restaging = Yes, then is_first should be No (not first if restaging)
    restaging_yes = result['mri_stage.is_restaging_mri_report'].astype(str).str.strip().str.lower() == 'yes'
    first_not_no = result['mri_stage.is_first_mri_report'].astype(str).str.strip().str.lower() != 'no'
    mask = restaging_yes & first_not_no
    result.loc[mask, 'mri_stage.is_first_mri_report'] = 'No'
    count('mri_stage_restaging_implies_not_first', mask)

    # ---------------------------------------------------------------
    # RULE 11: Numeric sanity clamping
    # ---------------------------------------------------------------
    # bio.age: ensure it's just a number, not "X mm"
    for i in range(n):
        age_val = str(result.at[result.index[i], 'bio.age']).strip()
        if 'mm' in age_val.lower():
            nums = re.findall(r'\d+', age_val)
            if nums:
                result.at[result.index[i], 'bio.age'] = nums[0]

    # For distance fields, clamp unreasonable values
    distance_fields = [
        'mri_numeric.distance_from_anal_verge',
        'mri_numeric.distance_from_anorectal_junction',
        'mri_numeric.extramural_spread_size',
        'mri_numeric.mr_crm_distance',
    ]
    for col in distance_fields:
        for i in range(n):
            val = str(result.at[result.index[i], col]).strip()
            nums = re.findall(r'\d+(?:\.\d+)?', val)
            if nums:
                v = float(nums[0])
                if 'cm' in val.lower():
                    v *= 10
                # Clamp extreme values (>200mm is suspicious for rectal measurements)
                if v > 200:
                    result.at[result.index[i], col] = 'Not Mentioned'

    # ---------------------------------------------------------------
    # RULE 12: Use Flan-T5-Large predictions as override for fields
    #          where the ensemble chose TF-IDF but Large is better
    # ---------------------------------------------------------------
    # (This is already handled by smart2, but we can double-check
    #  for fields where Large model prediction is more clinically sensible)

    # Print rule application summary
    print("\n--- Rule application summary ---")
    total_fixes = 0
    for rule, cnt in sorted(rule_counts.items(), key=lambda x: -x[1]):
        if cnt > 0:
            print(f"  {rule}: {cnt} corrections")
            total_fixes += cnt
    print(f"  TOTAL corrections: {total_fixes}")

    return result


# ------------------------------------------------------------------
# STEP 4: Apply rules to BOTH valid and test predictions
# ------------------------------------------------------------------

# Start from the best-of-3 ensemble
print("\n" + "=" * 70)
print("Applying rules to VALIDATION set...")
print("=" * 70)
ruled_vp = apply_rules(smart2_vp, valid_flat['text'], train_flat)

print("\n" + "=" * 70)
print("Applying rules to TEST set...")
print("=" * 70)
ruled_tp = apply_rules(smart2_tp, test_flat['text'], train_flat)


# ------------------------------------------------------------------
# STEP 5: Evaluate the rule-corrected predictions
# ------------------------------------------------------------------
ruled_vm = evaluate_predictions(valid_flat, ruled_vp, CAT_FIELDS, NUMERIC_FIELDS)
ruled_tm = evaluate_predictions(test_flat, ruled_tp, CAT_FIELDS, NUMERIC_FIELDS)

print("\n" + "=" * 70)
print("RESULTS AFTER RULE-BASED CORRECTIONS")
print("=" * 70)
print_metrics("\n[AFTER rules] Rule-Corrected Ensemble — VALID", ruled_vm)
print_metrics("[AFTER rules] Rule-Corrected Ensemble — TEST", ruled_tm)

# Show improvement
print("\n--- Improvement ---")
for metric in ['leaf_avg_cat_accuracy', 'micro_cat_accuracy', 'leaf_avg_macro_f1']:
    before_v = before_vm[metric]
    after_v = ruled_vm[metric]
    delta = after_v - before_v
    print(f"  VALID {metric}: {before_v:.4f} -> {after_v:.4f} ({delta:+.4f})")
for metric in ['leaf_avg_cat_accuracy', 'micro_cat_accuracy', 'leaf_avg_macro_f1']:
    before_t = before_tm[metric]
    after_t = ruled_tm[metric]
    delta = after_t - before_t
    print(f"  TEST  {metric}: {before_t:.4f} -> {after_t:.4f} ({delta:+.4f})")


# ------------------------------------------------------------------
# STEP 6: Per-field accuracy comparison (before vs after)
# ------------------------------------------------------------------
err_before = per_field_accuracy(valid_flat, smart2_vp, ALL_FIELDS)
err_after = per_field_accuracy(valid_flat, ruled_vp, ALL_FIELDS)

comparison = err_before.merge(err_after, on='field', suffixes=('_before', '_after'))
comparison['delta'] = comparison['accuracy_after'] - comparison['accuracy_before']
comparison = comparison.sort_values('delta', ascending=False)

print("\n" + "=" * 70)
print("PER-FIELD ACCURACY CHANGES (improved fields)")
print("=" * 70)
improved = comparison[comparison['delta'] > 0]
for _, row in improved.iterrows():
    print(f"  {row['field']:60s} {row['accuracy_before']:.0%} -> {row['accuracy_after']:.0%} "
          f"({row['delta']:+.0%}, {row['n_errors_before']-row['n_errors_after']:+d} errors fixed)")

worsened = comparison[comparison['delta'] < 0]
if len(worsened) > 0:
    print(f"\nWORSENED fields ({len(worsened)}):")
    for _, row in worsened.iterrows():
        print(f"  {row['field']:60s} {row['accuracy_before']:.0%} -> {row['accuracy_after']:.0%} "
              f"({row['delta']:+.0%})")

unchanged = comparison[comparison['delta'] == 0]
print(f"\nUnchanged fields: {len(unchanged)}")


# ------------------------------------------------------------------
# STEP 7: Remaining errors — what still needs fixing
# ------------------------------------------------------------------
err_final = per_field_accuracy(valid_flat, ruled_vp, ALL_FIELDS)
err_final = err_final.sort_values('accuracy')

print("\n" + "=" * 70)
print("REMAINING WORST FIELDS (after rules)")
print("=" * 70)
print(err_final.head(20).to_string(index=False))

n100 = (err_final['accuracy'] == 1.0).sum()
n90 = (err_final['accuracy'] >= 0.9).sum()
n80 = (err_final['accuracy'] >= 0.8).sum()
print(f"\nFields at 100%: {n100}/{len(ALL_FIELDS)}")
print(f"Fields at >=90%: {n90}/{len(ALL_FIELDS)}")
print(f"Fields at >=80%: {n80}/{len(ALL_FIELDS)}")
print(f"Average field accuracy: {err_final['accuracy'].mean():.3f}")


# ------------------------------------------------------------------
# STEP 8: Show specific remaining errors for debugging
# ------------------------------------------------------------------
print("\n" + "=" * 70)
print("SPECIFIC REMAINING ERRORS (worst 10 fields)")
print("=" * 70)
for field in err_final.head(10)['field'].tolist():
    yt = valid_flat[field].astype(str).tolist()
    yp = ruled_vp[field].astype(str).tolist()
    errors = [(t, p) for t, p in zip(yt, yp)
              if t.strip().lower() != p.strip().lower()]
    if errors:
        print(f"\n{field} ({len(errors)} errors):")
        for t, p in errors[:5]:
            print(f"  TRUE: {t!r:40s} PRED: {p!r}")


# ------------------------------------------------------------------
# STEP 9: Final comparison table
# ------------------------------------------------------------------
print("\n" + "=" * 70)
print("FINAL COMPARISON TABLE")
print("=" * 70)

final_results = pd.DataFrame([
    fmt('Majority', 'VALID', maj_vm), fmt('Majority', 'TEST', maj_tm),
    fmt('TF-IDF', 'VALID', tfidf_vm), fmt('TF-IDF', 'TEST', tfidf_tm),
    fmt('Flan-T5-Base v2', 'VALID', flan_vm2), fmt('Flan-T5-Base v2', 'TEST', flan_tm2),
    fmt('Flan-T5-Large', 'VALID', flan_l_vm), fmt('Flan-T5-Large', 'TEST', flan_l_tm),
    fmt('Best-of-3', 'VALID', before_vm), fmt('Best-of-3', 'TEST', before_tm),
    fmt('Best-of-3 + Rules', 'VALID', ruled_vm), fmt('Best-of-3 + Rules', 'TEST', ruled_tm),
])
display(final_results)


# ------------------------------------------------------------------
# STEP 10: Save results
# ------------------------------------------------------------------
OUT = '/content/results_v3_ruled'
os.makedirs(OUT, exist_ok=True)
ruled_vp.to_csv(f'{OUT}/ruled_ensemble_valid.csv', index=False)
ruled_tp.to_csv(f'{OUT}/ruled_ensemble_test.csv', index=False)
err_final.to_csv(f'{OUT}/per_field_accuracy_ruled.csv', index=False)
final_results.to_csv(f'{OUT}/final_comparison_v3.csv', index=False)
comparison.to_csv(f'{OUT}/per_field_before_after.csv', index=False)
print(f'\nSaved to {OUT}')

try:
    from google.colab import files
    for f in os.listdir(OUT):
        files.download(f'{OUT}/{f}')
except:
    pass

RULE-BASED CONSTRAINT LAYER


[BEFORE rules] Best-of-3 — VALID
  leaf_avg_cat_accuracy: 0.8146341463414634
  leaf_avg_macro_f1: 0.6297625322387252
  micro_cat_accuracy: 0.8146341463414634
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

[BEFORE rules] Best-of-3 — TEST
  leaf_avg_cat_accuracy: 0.7847560975609755
  leaf_avg_macro_f1: 0.5353305494065891
  micro_cat_accuracy: 0.7847560975609756
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Fields where 'Not Mentioned' is rare in training (<10%): 20
  adjacent_structures_t4b.female.uterus                        -> default='not applicable' (NM=6% in train)
  adjacent_structures_t4b.female.vagina                        -> default='not applicable' (NM=6% in train)
  adjacent_structures_t4b.male.prostate                        -> default='no' (NM=3% in train)
  adjacent_structures_t4b.male.seminal_vesicles                -> default='no' (NM=9% in train)
  adjacent_structures_t4b.male_and_female.p

,Model,Split,Cat Acc,Macro F1,Micro Acc,Exact Match
0,Majority,VALID,0.5963,0.3395,0.5963,0
1,Majority,TEST,0.6360,0.3066,0.6360,0
2,TF-IDF,VALID,0.7549,0.5595,0.7549,0
3,TF-IDF,TEST,0.7091,0.4707,0.7091,0
4,Flan-T5-Base v2,VALID,0.5524,0.3560,0.5524,0
5,Flan-T5-Base v2,TEST,0.5713,0.3234,0.5713,0
6,Flan-T5-Large,VALID,0.6280,0.4526,0.6280,0
7,Flan-T5-Large,TEST,0.6335,0.4303,0.6335,0
8,Best-of-3,VALID,0.8146,0.6298,0.8146,0
9,Best-of-3,TEST,0.7848,0.5353,0.7848,0



Saved to /content/results_v3_ruled


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## Step 17: Strategy A — LLM Few-Shot Extraction with Gemini 2.0 Flash

Having exhausted fine-tuning-based approaches (~81.5% accuracy), we try a fundamentally different strategy: using a large pre-trained LLM (Gemini 2.0 Flash) to extract all 54 fields in a **single pass** without any fine-tuning.

### Approach
1. **Retrieval-augmented few-shot**: For each test report, retrieve the 3 most similar training reports (by TF-IDF cosine similarity) as in-context examples
2. **Schema-guided extraction**: The prompt includes the full schema with valid values for each field
3. **JSON-structured output**: Request `response_mime_type="application/json"` for reliable parsing

### Hypothesis
A 27B+ parameter model with broad medical knowledge should outperform a 780M model fine-tuned on only 65 examples.

### Actual Result
The Gemini approach scored **only ~36% accuracy** — far below expectations. Per-field analysis showed 0% accuracy on basic fields like `report_type`, `bio.age`, and `bio.gender`, indicating a **format mismatch** between Gemini's JSON output and the expected ground-truth encoding rather than a comprehension failure. The hybrid ensemble defaults back to the fine-tuned models for all fields where Gemini underperforms.

> **Lesson learned:** LLM-based extraction requires careful output format alignment (value normalisation, handling of missing-value markers, unit formatting) to match the specific annotation conventions in the ground-truth data. The raw LLM output is likely clinically correct but formatted differently from the training labels.

In [18]:
# ============================================================
# STRATEGY A: LLM Few-Shot Extraction with Gemini 2.0 Flash
# ============================================================
# This replaces field-by-field fine-tuned extraction with a
# single-pass LLM call that extracts ALL 54 fields at once.
#
# Key advantages:
#   - Gemini already understands medical terminology (no fine-tuning needed)
#   - Single-pass extraction captures cross-field dependencies
#   - Retrieval-augmented few-shot gives the most relevant examples
#   - Free tier: 15 RPM / 1M tokens/min on Gemini 2.0 Flash
#
# Prerequisites:
#   !pip install -q google-generativeai scikit-learn
#   Get API key from https://aistudio.google.com/apikey
#
# This cell expects all variables from cells 0–14 to be present.
# ============================================================

!pip install -q google-generativeai

import google.generativeai as genai
import json, ast, re, time, os
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ----- CONFIG -----


# Using Colab secrets (recommended):
try:
    from google.colab import userdata
    GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
except:
    pass

assert GEMINI_API_KEY, "Please set GEMINI_API_KEY above or in Colab Secrets!"
genai.configure(api_key=GEMINI_API_KEY)

# Choose the model — Gemini 2.0 Flash is free and very capable
MODEL_ID = "gemini-2.0-flash"
print(f"Using model: {MODEL_ID}")


# ==================================================================
# PART 1: Build the retrieval index for few-shot example selection
# ==================================================================
# For each test report, find the 3 most similar training reports
# using TF-IDF cosine similarity. This gives the LLM demonstrations
# that match the vocabulary and style of the input report.
# ==================================================================

print("\n--- Building retrieval index ---")

# Build TF-IDF vectors over training reports
retrieval_vec = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=20000,
    min_df=1,
    sublinear_tf=True
)
train_tfidf = retrieval_vec.fit_transform(train_flat['text'].astype(str))
print(f"Retrieval index built: {train_tfidf.shape}")


def get_similar_examples(query_text, n=3):
    """
    Find the n most similar training reports to the query.
    Returns list of (text, output_dict) tuples.
    """
    q_vec = retrieval_vec.transform([str(query_text)])
    sims = cosine_similarity(q_vec, train_tfidf).flatten()
    top_idx = sims.argsort()[-n:][::-1]

    examples = []
    for idx in top_idx:
        row = train_flat.iloc[idx]
        # Reconstruct the output dict from flat columns
        output_dict = {}
        for col in ALL_FIELDS:
            output_dict[col] = str(row[col])
        examples.append({
            'text': str(row['text']),
            'output': output_dict,
            'similarity': float(sims[idx])
        })
    return examples


# ==================================================================
# PART 2: Build the extraction prompt
# ==================================================================
# The prompt includes:
#   - Detailed schema description with valid values
#   - 3 retrieved few-shot examples (most similar to the input)
#   - The target report
#   - Instructions to output ONLY a JSON object
# ==================================================================

# Build the valid-values reference from training data
def get_valid_values(col, train_df):
    """Get the set of values seen in training for a field."""
    vals = train_df[col].astype(str).unique().tolist()
    # Clean and sort
    vals = sorted(set(v.strip() for v in vals if v.strip()))
    return vals

FIELD_VALID_VALUES = {}
for col in ALL_FIELDS:
    FIELD_VALID_VALUES[col] = get_valid_values(col, train_flat)

# Build schema description string
def build_schema_description():
    """Create a compact schema reference for the prompt."""
    lines = []
    for col in ALL_FIELDS:
        vals = FIELD_VALID_VALUES[col]
        desc = FIELD_DESC.get(col, col)
        # Truncate value list if too long
        if len(vals) > 10:
            val_str = ", ".join(vals[:8]) + f" ... ({len(vals)} values)"
        else:
            val_str = ", ".join(vals)
        lines.append(f'  "{col}": {desc} — valid values: [{val_str}]')
    return "\n".join(lines)

SCHEMA_DESC = build_schema_description()


def build_extraction_prompt(report_text, examples):
    """
    Build the full prompt for extracting structured fields.

    Args:
        report_text: The MRI report to extract from
        examples: List of similar examples from retrieval
    Returns:
        Prompt string
    """

    # System instructions
    system = (
        "You are an expert radiologist extracting structured data from "
        "rectal cancer MRI reports. You must extract EXACTLY the fields "
        "listed in the schema below. Output ONLY a valid JSON object with "
        "all field names as keys.\n\n"
        "CRITICAL RULES:\n"
        "1. Use ONLY values from the valid values list for each field.\n"
        "2. If information is not found in the report, use 'Not Mentioned'.\n"
        "3. If a field does not apply (e.g., female anatomy for male patient), "
        "use 'Not Applicable'.\n"
        "4. If findings are nil/unremarkable, use 'Nil Significant'.\n"
        "5. For numeric fields (measurements), include the unit (e.g., '25 mm').\n"
        "6. For bio.age, output ONLY the number (e.g., '57'), no units.\n"
        "7. Gender-specific fields: For male patients, set female-only fields "
        "(ovaries, uterus, vagina) to 'Not Applicable' and vice versa.\n"
        "8. MR TRG is only applicable for post-treatment/restaging MRIs.\n"
        "9. Read the ENTIRE report carefully before answering. Pay special "
        "attention to the CONCLUSION/IMPRESSION section for staging.\n"
        "10. Output ONLY the JSON object. No markdown, no explanation, no "
        "backticks.\n"
    )

    # Schema reference
    schema_section = f"\n--- SCHEMA (all fields must be present) ---\n{SCHEMA_DESC}\n"

    # Few-shot examples
    example_section = "\n--- EXAMPLES ---\n"
    for i, ex in enumerate(examples, 1):
        example_section += f"\nExample {i} (similarity: {ex['similarity']:.2f}):\n"
        example_section += f"REPORT:\n{ex['text'][:2000]}\n"  # truncate long reports
        example_section += f"OUTPUT:\n{json.dumps(ex['output'], indent=None)}\n"

    # Target report
    target_section = (
        f"\n--- NOW EXTRACT FROM THIS REPORT ---\n"
        f"REPORT:\n{report_text}\n\n"
        f"OUTPUT (JSON only, all {len(ALL_FIELDS)} fields):\n"
    )

    return system + schema_section + example_section + target_section


# ==================================================================
# PART 3: Call the Gemini API with retry logic
# ==================================================================

def call_gemini(prompt, max_retries=3):
    """
    Call Gemini API with retry logic and rate limiting.
    Returns the raw text response.
    """
    model = genai.GenerativeModel(MODEL_ID)

    for attempt in range(max_retries):
        try:
            response = model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.0,       # deterministic for extraction
                    max_output_tokens=2048,
                    # Request JSON output
                    response_mime_type="application/json",
                ),
            )
            return response.text
        except Exception as e:
            err_str = str(e)
            if '429' in err_str or 'quota' in err_str.lower():
                # Rate limited — wait and retry
                wait = 15 * (attempt + 1)
                print(f"  Rate limited, waiting {wait}s...")
                time.sleep(wait)
            elif '500' in err_str or '503' in err_str:
                # Server error — brief retry
                time.sleep(5)
            else:
                print(f"  API error: {e}")
                if attempt == max_retries - 1:
                    return None
                time.sleep(3)
    return None


def parse_llm_response(response_text, train_ref):
    """
    Parse the LLM's JSON response into a dict with validated values.

    Args:
        response_text: Raw text from LLM
        train_ref: Training DataFrame for value validation
    Returns:
        Dict mapping field names to extracted values
    """
    if response_text is None:
        # Fallback: return all "Not Mentioned"
        return {col: 'Not Mentioned' for col in ALL_FIELDS}

    # Clean the response — strip markdown code fences if present
    text = response_text.strip()
    text = re.sub(r'^```(?:json)?\s*', '', text)
    text = re.sub(r'\s*```$', '', text)

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        # Try to extract JSON from the response
        json_match = re.search(r'\{[\s\S]*\}', text)
        if json_match:
            try:
                parsed = json.loads(json_match.group())
            except:
                print(f"  WARNING: Could not parse JSON response")
                return {col: 'Not Mentioned' for col in ALL_FIELDS}
        else:
            print(f"  WARNING: No JSON found in response")
            return {col: 'Not Mentioned' for col in ALL_FIELDS}

    # Validate and fill missing fields
    result = {}
    for col in ALL_FIELDS:
        val = parsed.get(col, 'Not Mentioned')
        val = str(val).strip()

        # Normalize common variants
        val_lower = val.lower()
        normalize_map = {
            'not mentioned': 'Not Mentioned',
            'not applicable': 'Not Applicable',
            'nil significant': 'Nil Significant',
            'not relevant': 'Not Relevant',
        }
        if val_lower in normalize_map:
            result[col] = normalize_map[val_lower]
            continue

        # Try to match against known training values (fuzzy)
        known = {v.strip().lower(): v for v in
                 train_ref[col].astype(str).unique()}
        if val_lower in known:
            result[col] = known[val_lower]
        else:
            # Keep the LLM's output but check for close matches
            best_match = None
            for kl, kv in known.items():
                if len(kl) > 3 and (kl in val_lower or val_lower in kl):
                    best_match = kv
                    break
            result[col] = best_match if best_match else val

    return result


# ==================================================================
# PART 4: Run extraction on validation and test sets
# ==================================================================

def extract_dataset(df, split_name, n_examples=3):
    """
    Extract fields for all reports in a DataFrame.

    Args:
        df: DataFrame with 'text' column
        split_name: "VALID" or "TEST" for logging
        n_examples: Number of few-shot examples to retrieve
    Returns:
        DataFrame with predictions for all fields
    """
    all_preds = []
    texts = df['text'].astype(str).tolist()

    print(f"\n{'='*60}")
    print(f"Extracting {split_name} set ({len(texts)} reports)")
    print(f"{'='*60}")

    for i, text in enumerate(texts):
        print(f"\n[{i+1}/{len(texts)}] Processing report {i+1}...")

        # Retrieve similar training examples
        examples = get_similar_examples(text, n=n_examples)
        sim_scores = [f"{ex['similarity']:.2f}" for ex in examples]
        print(f"  Retrieved examples (similarities: {', '.join(sim_scores)})")

        # Build prompt and call API
        prompt = build_extraction_prompt(text, examples)
        print(f"  Prompt length: {len(prompt)} chars")

        response = call_gemini(prompt)

        # Parse response
        preds = parse_llm_response(response, train_flat)

        # Count non-default values as a sanity check
        non_default = sum(1 for v in preds.values()
                         if v not in ('Not Mentioned', 'Not Applicable',
                                      'Nil Significant', 'Not Relevant'))
        print(f"  Extracted {non_default}/{len(ALL_FIELDS)} non-default values")

        all_preds.append(preds)

        # Rate limiting: be gentle with the free tier
        time.sleep(4)  # ~15 RPM limit

    return pd.DataFrame(all_preds)


# --- Run on validation set ---
print("Starting validation set extraction...")
llm_vp = extract_dataset(valid_flat, "VALID", n_examples=3)

# --- Evaluate ---
llm_vm = evaluate_predictions(valid_flat, llm_vp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('\nGemini LLM Few-Shot — VALID', llm_vm)

# --- Run on test set ---
print("\nStarting test set extraction...")
llm_tp = extract_dataset(test_flat, "TEST", n_examples=3)

llm_tm = evaluate_predictions(test_flat, llm_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('\nGemini LLM Few-Shot — TEST', llm_tm)


# ==================================================================
# PART 5: Per-field accuracy analysis
# ==================================================================
llm_err = per_field_accuracy(valid_flat, llm_vp, ALL_FIELDS)
print('\n=== LLM Per-field accuracy (worst first) ===')
print(llm_err.head(20).to_string(index=False))

n100 = (llm_err['accuracy'] == 1.0).sum()
n90 = (llm_err['accuracy'] >= 0.9).sum()
n80 = (llm_err['accuracy'] >= 0.8).sum()
print(f'\nFields at 100%: {n100}/{len(ALL_FIELDS)}')
print(f'Fields at >=90%: {n90}/{len(ALL_FIELDS)}')
print(f'Fields at >=80%: {n80}/{len(ALL_FIELDS)}')
print(f'Average: {llm_err["accuracy"].mean():.3f}')


# ==================================================================
# PART 6: Compare with previous best
# ==================================================================
print('\n' + '=' * 60)
print('COMPARISON: Previous Best vs LLM')
print('=' * 60)

# Per-field improvement
prev_err = per_field_accuracy(valid_flat, smart2_vp, ALL_FIELDS)
merged = prev_err.merge(llm_err, on='field', suffixes=('_prev', '_llm'))
merged['delta'] = merged['accuracy_llm'] - merged['accuracy_prev']
merged = merged.sort_values('delta', ascending=False)

improved = merged[merged['delta'] > 0]
print(f'\nImproved fields ({len(improved)}):')
for _, row in improved.iterrows():
    print(f"  {row['field']:55s} {row['accuracy_prev']:.0%} -> {row['accuracy_llm']:.0%} ({row['delta']:+.0%})")

worsened = merged[merged['delta'] < 0]
if len(worsened) > 0:
    print(f'\nWorsened fields ({len(worsened)}):')
    for _, row in worsened.iterrows():
        print(f"  {row['field']:55s} {row['accuracy_prev']:.0%} -> {row['accuracy_llm']:.0%} ({row['delta']:+.0%})")

# Final comparison table
final_llm = pd.DataFrame([
    fmt('Majority', 'VALID', maj_vm), fmt('Majority', 'TEST', maj_tm),
    fmt('TF-IDF', 'VALID', tfidf_vm), fmt('TF-IDF', 'TEST', tfidf_tm),
    fmt('Best-of-3', 'VALID', before_vm), fmt('Best-of-3', 'TEST', before_tm),
    fmt('Best-of-3 + Rules', 'VALID', ruled_vm), fmt('Best-of-3 + Rules', 'TEST', ruled_tm),
    fmt('Gemini LLM', 'VALID', llm_vm), fmt('Gemini LLM', 'TEST', llm_tm),
])
display(final_llm)


# ==================================================================
# PART 7: Hybrid ensemble — take the best of LLM vs previous
# ==================================================================
print('\n' + '=' * 60)
print('HYBRID: Best-of-all per-field ensemble')
print('=' * 60)

acc_llm = get_per_field_acc(valid_flat, llm_vp, ALL_FIELDS)
acc_prev = get_per_field_acc(valid_flat, smart2_vp, ALL_FIELDS)

hybrid_vp = pd.DataFrame(index=valid_flat.index)
hybrid_tp = pd.DataFrame(index=test_flat.index)

for col in ALL_FIELDS:
    if acc_llm.get(col, 0) >= acc_prev.get(col, 0):
        hybrid_vp[col] = llm_vp[col]
        hybrid_tp[col] = llm_tp[col]
    else:
        hybrid_vp[col] = smart2_vp[col]
        hybrid_tp[col] = smart2_tp[col]

hybrid_vm = evaluate_predictions(valid_flat, hybrid_vp, CAT_FIELDS, NUMERIC_FIELDS)
hybrid_tm = evaluate_predictions(test_flat, hybrid_tp, CAT_FIELDS, NUMERIC_FIELDS)
print_metrics('HYBRID (best per field) — VALID', hybrid_vm)
print_metrics('HYBRID (best per field) — TEST', hybrid_tm)


# ==================================================================
# PART 8: Save everything
# ==================================================================
OUT = '/content/results_llm'
os.makedirs(OUT, exist_ok=True)
llm_vp.to_csv(f'{OUT}/llm_valid_pred.csv', index=False)
llm_tp.to_csv(f'{OUT}/llm_test_pred.csv', index=False)
hybrid_vp.to_csv(f'{OUT}/hybrid_valid_pred.csv', index=False)
hybrid_tp.to_csv(f'{OUT}/hybrid_test_pred.csv', index=False)
llm_err.to_csv(f'{OUT}/llm_per_field_accuracy.csv', index=False)
final_llm.to_csv(f'{OUT}/final_comparison_llm.csv', index=False)
print(f'\nSaved to {OUT}')

try:
    from google.colab import files
    for f in os.listdir(OUT):
        files.download(f'{OUT}/{f}')
except:
    pass


/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning: 

All support for the `google.generativeai` package has ended. It will no longer be receiving 
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)


Using model: gemini-2.0-flash

--- Building retrieval index ---
Retrieval index built: (65, 5142)
Starting validation set extraction...

Extracting VALID set (20 reports)

[1/20] Processing report 1...
  Retrieved examples (similarities: 0.35, 0.29, 0.29)
  Prompt length: 22683 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[2/20] Processing report 2...
  Retrieved examples (similarities: 0.37, 0.34, 0.34)
  Prompt length: 24050 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[3/20] Processing report 3...
  Retrieved examples (similarities: 0.45, 0.40, 0.39)
  Prompt length: 23264 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[4/20] Processing report 4...
  Retrieved examples (similarities: 0.18, 0.17, 0.16)
  Prompt length: 22745 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[5/20] Processing report 5...
  Retrieved examples (similarities: 0.28, 0.25, 0.23)
  Prompt length: 23632 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[6/20] Processing report 6...
  Retrieved examples (similarities: 0.42, 0.41, 0.40)
  Prompt length: 23812 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[7/20] Processing report 7...
  Retrieved examples (similarities: 0.42, 0.41, 0.38)
  Prompt length: 22814 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[8/20] Processing report 8...
  Retrieved examples (similarities: 0.21, 0.20, 0.20)
  Prompt length: 25242 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[9/20] Processing report 9...
  Retrieved examples (similarities: 0.34, 0.34, 0.33)
  Prompt length: 23272 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[10/20] Processing report 10...
  Retrieved examples (similarities: 0.36, 0.35, 0.34)
  Prompt length: 23046 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[11/20] Processing report 11...
  Retrieved examples (similarities: 0.43, 0.32, 0.31)
  Prompt length: 22795 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[12/20] Processing report 12...
  Retrieved examples (similarities: 0.35, 0.31, 0.29)
  Prompt length: 23384 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[13/20] Processing report 13...
  Retrieved examples (similarities: 0.23, 0.20, 0.18)
  Prompt length: 22784 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[14/20] Processing report 14...
  Retrieved examples (similarities: 0.39, 0.30, 0.30)
  Prompt length: 23154 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[15/20] Processing report 15...
  Retrieved examples (similarities: 0.50, 0.44, 0.44)
  Prompt length: 22799 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[16/20] Processing report 16...
  Retrieved examples (similarities: 0.33, 0.31, 0.29)
  Prompt length: 23692 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[17/20] Processing report 17...
  Retrieved examples (similarities: 0.36, 0.31, 0.27)
  Prompt length: 23125 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[18/20] Processing report 18...
  Retrieved examples (similarities: 0.38, 0.31, 0.28)
  Prompt length: 23119 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[19/20] Processing report 19...
  Retrieved examples (similarities: 0.35, 0.32, 0.30)
  Prompt length: 23307 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[20/20] Processing report 20...
  Retrieved examples (similarities: 0.31, 0.29, 0.27)
  Prompt length: 23983 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values


Gemini LLM Few-Shot — VALID
  leaf_avg_cat_accuracy: 0.3597560975609756
  leaf_avg_macro_f1: 0.2367593994040802
  micro_cat_accuracy: 0.3597560975609756
  record_exact_match: 0.0
  numeric_mae_mm: None
  numeric_rmse_mm: None

Starting test set extraction...

Extracting TEST set (40 reports)

[1/40] Processing report 1...
  Retrieved examples (similarities: 0.26, 0.23, 0.22)
  Prompt length: 24059 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[2/40] Processing report 2...
  Retrieved examples (similarities: 0.44, 0.42, 0.41)
  Prompt length: 23994 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[3/40] Processing report 3...
  Retrieved examples (similarities: 0.35, 0.31, 0.30)
  Prompt length: 24958 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[4/40] Processing report 4...
  Retrieved examples (similarities: 0.30, 0.27, 0.27)
  Prompt length: 23818 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[5/40] Processing report 5...
  Retrieved examples (similarities: 0.16, 0.14, 0.14)
  Prompt length: 23541 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[6/40] Processing report 6...
  Retrieved examples (similarities: 0.44, 0.43, 0.39)
  Prompt length: 22888 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[7/40] Processing report 7...
  Retrieved examples (similarities: 0.55, 0.37, 0.32)
  Prompt length: 22923 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[8/40] Processing report 8...
  Retrieved examples (similarities: 0.41, 0.40, 0.38)
  Prompt length: 24014 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[9/40] Processing report 9...
  Retrieved examples (similarities: 0.56, 0.37, 0.35)
  Prompt length: 22960 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[10/40] Processing report 10...
  Retrieved examples (similarities: 0.47, 0.42, 0.39)
  Prompt length: 25023 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[11/40] Processing report 11...
  Retrieved examples (similarities: 0.33, 0.29, 0.27)
  Prompt length: 23431 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[12/40] Processing report 12...
  Retrieved examples (similarities: 0.25, 0.23, 0.22)
  Prompt length: 23139 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[13/40] Processing report 13...
  Retrieved examples (similarities: 0.34, 0.30, 0.22)
  Prompt length: 23706 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[14/40] Processing report 14...
  Retrieved examples (similarities: 0.38, 0.36, 0.29)
  Prompt length: 23363 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[15/40] Processing report 15...
  Retrieved examples (similarities: 0.40, 0.36, 0.34)
  Prompt length: 23389 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[16/40] Processing report 16...
  Retrieved examples (similarities: 0.58, 0.39, 0.35)
  Prompt length: 23648 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[17/40] Processing report 17...
  Retrieved examples (similarities: 0.30, 0.29, 0.26)
  Prompt length: 23764 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[18/40] Processing report 18...
  Retrieved examples (similarities: 0.26, 0.26, 0.22)
  Prompt length: 23033 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[19/40] Processing report 19...
  Retrieved examples (similarities: 0.40, 0.30, 0.28)
  Prompt length: 23748 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[20/40] Processing report 20...
  Retrieved examples (similarities: 0.38, 0.31, 0.30)
  Prompt length: 23049 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[21/40] Processing report 21...
  Retrieved examples (similarities: 0.48, 0.38, 0.37)
  Prompt length: 23306 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[22/40] Processing report 22...
  Retrieved examples (similarities: 0.31, 0.31, 0.29)
  Prompt length: 23086 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[23/40] Processing report 23...
  Retrieved examples (similarities: 0.28, 0.27, 0.24)
  Prompt length: 25321 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[24/40] Processing report 24...
  Retrieved examples (similarities: 0.33, 0.32, 0.31)
  Prompt length: 23775 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[25/40] Processing report 25...
  Retrieved examples (similarities: 0.32, 0.31, 0.29)
  Prompt length: 23420 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[26/40] Processing report 26...
  Retrieved examples (similarities: 0.54, 0.39, 0.36)
  Prompt length: 22871 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[27/40] Processing report 27...
  Retrieved examples (similarities: 0.42, 0.38, 0.37)
  Prompt length: 24009 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[28/40] Processing report 28...
  Retrieved examples (similarities: 0.36, 0.36, 0.35)
  Prompt length: 22897 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[29/40] Processing report 29...
  Retrieved examples (similarities: 0.24, 0.24, 0.24)
  Prompt length: 24187 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[30/40] Processing report 30...
  Retrieved examples (similarities: 0.21, 0.19, 0.18)
  Prompt length: 23452 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[31/40] Processing report 31...
  Retrieved examples (similarities: 0.28, 0.28, 0.27)
  Prompt length: 23802 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[32/40] Processing report 32...
  Retrieved examples (similarities: 0.25, 0.25, 0.24)
  Prompt length: 23266 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[33/40] Processing report 33...
  Retrieved examples (similarities: 0.50, 0.45, 0.41)
  Prompt length: 24098 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[34/40] Processing report 34...
  Retrieved examples (similarities: 0.38, 0.33, 0.33)
  Prompt length: 23538 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[35/40] Processing report 35...
  Retrieved examples (similarities: 0.29, 0.23, 0.23)
  Prompt length: 24226 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[36/40] Processing report 36...
  Retrieved examples (similarities: 0.20, 0.20, 0.19)
  Prompt length: 23256 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[37/40] Processing report 37...
  Retrieved examples (similarities: 0.26, 0.22, 0.19)
  Prompt length: 23693 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[38/40] Processing report 38...
  Retrieved examples (similarities: 0.42, 0.33, 0.32)
  Prompt length: 24862 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[39/40] Processing report 39...
  Retrieved examples (similarities: 0.31, 0.29, 0.28)
  Prompt length: 23988 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values

[40/40] Processing report 40...
  Retrieved examples (similarities: 0.26, 0.26, 0.25)
  Prompt length: 24014 chars


  Rate limited, waiting 15s...


  Rate limited, waiting 30s...


  Rate limited, waiting 45s...
  Extracted 0/54 non-default values


Gemini LLM Few-Shot — TEST
  leaf_avg_cat_accuracy: 0.3670731707317073
  leaf_avg_macro_f1: 0.19970303287762986
  micro_cat_accuracy: 0.3670731707317073
  record_exact_match: 0.0
  numeric_mae_mm: None
  numeric_rmse_mm: None

=== LLM Per-field accuracy (worst first) ===
                                        field  accuracy  n_errors
                                  report_type      0.00        20
                                      bio.age      0.00        20
                                   bio.gender      0.00        20
        adjacent_structures_t4b.male.prostate      0.00        20
adjacent_structures_t4b.male.seminal_vesicles      0.00        20
                                      n_stage      0.00        20
       mri_numeric.number_of_mesorectal_nodes      0.05        19
         mri_numeric.current_length_of_tumour      0.05        19
        adjacent_structures_t4b.female.uterus      0.05        19

,Model,Split,Cat Acc,Macro F1,Micro Acc,Exact Match
0,Majority,VALID,0.5963,0.3395,0.5963,0
1,Majority,TEST,0.6360,0.3066,0.6360,0
2,TF-IDF,VALID,0.7549,0.5595,0.7549,0
3,TF-IDF,TEST,0.7091,0.4707,0.7091,0
4,Best-of-3,VALID,0.8146,0.6298,0.8146,0
5,Best-of-3,TEST,0.7848,0.5353,0.7848,0
6,Best-of-3 + Rules,VALID,0.8159,0.6300,0.8159,0
7,Best-of-3 + Rules,TEST,0.7909,0.5452,0.7909,0
8,Gemini LLM,VALID,0.3598,0.2368,0.3598,0
9,Gemini LLM,TEST,0.3671,0.1997,0.3671,0



HYBRID: Best-of-all per-field ensemble

HYBRID (best per field) — VALID
  leaf_avg_cat_accuracy: 0.8146341463414634
  leaf_avg_macro_f1: 0.6287440385373048
  micro_cat_accuracy: 0.8146341463414634
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

HYBRID (best per field) — TEST
  leaf_avg_cat_accuracy: 0.7865853658536583
  leaf_avg_macro_f1: 0.5297653958418289
  micro_cat_accuracy: 0.7865853658536586
  record_exact_match: 0.0
  numeric_mae_mm: nan
  numeric_rmse_mm: nan

Saved to /content/results_llm


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>